### ISSUE TITLE
Error shows up while running deploy_glastoph.sh

### ISSUE THREAD

**Issue by deanboole** [threatstream/mhn#123]
Hi 

Read https://github.com/threatstream/mhn/wiki/Getting-up-and-running-using-Vagrant
and I tried to run deploy_glastoph.sh on honeypot vm.

However, I the following msgs promt up, 

+ cd distribute-0.6.35
+ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    exec(init_file.read(), d)
  File "<string>", line 8, in <module>
  File "/root/distribute-0.6.35/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/root/distribute-0.6.35/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/root/distribute-0.6.35/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/root/distribute-0.6.35/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/root/distribute-0.6.35/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/root/distribute-0.6.35/pkg_resources.py", line 2825, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/root/distribute-0.6.35/pkg_resources.py", line 710, in subscribe
    callback(dist)
  File "/root/distribute-0.6.35/pkg_resources.py", line 2825, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/root/distribute-0.6.35/pkg_resources.py", line 2257, in activate
    self.insert_on(path)
  File "/root/distribute-0.6.35/pkg_resources.py", line 2352, in insert_on
    version = self.version
  File "/root/distribute-0.6.35/pkg_resources.py", line 2209, in version
    for line in self._get_metadata(self.PKG_INFO):
  File "/root/distribute-0.6.35/pkg_resources.py", line 2251, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/root/distribute-0.6.35/pkg_resources.py", line 1549, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/root/distribute-0.6.35/pkg_resources.py", line 1542, in get_metadata
    f = open(self.path,'rU')
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/setuptools.egg-info'

Is it a bug? How can I get rid of this problem? :-D

**Comment by jt6211** [comment]
What OS and version?

**Comment by deanboole** [comment]
root@mhn-honeypot:~# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04 LTS"

Thanks : )

**Comment by jt6211** [comment]
@deanboole I was able to reproduce these errors but not able to fix yet.

**Comment by sidra-asa** [comment]
I commented out the following line in deploy_glastoph.sh and the installation seemed to work.

	pip uninstall --yes setuptools

I think that it may cause some dependency problems.

**Comment by X4mp** [comment]
deploying glastopf failed for me because setuptools were not found.
commenting on the line as suggested by @sidra-asa  solved it for me.
Can this patch be applied to the general deploy.sh script for glastopf?
