### ISSUE TITLE
Unable to start mnemosyne - ERROR (abnormal termination)

### ISSUE THREAD

**Issue by Ryuz3n** [threatstream/mhn#153]
Hi!

Just installed MHN but I'm unable to run mnemosyne, always getting: "*mnemosyne: ERROR (abnormal termination)*". I've tried both in Ubuntu 14.04 x64 and Ubuntu 12.04 x32 machines, but always getting the same result.

**mnemosyne.err** shows:
>Traceback (most recent call last):
  File "runner.py", line 31, in <module>
    from webapi import mnemowebapi
  File "/opt/mnemosyne/webapi/mnemowebapi.py", line 26, in <module>
    from bottle.ext import mongo
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/bottle.py", line 1881, in load_module
    __import__(realname)
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/bottle_mongo.py", line 3, in <module>
    from pymongo import Connection
ImportError: cannot import name Connection

I've tried restarting MongoDB before trying to start mnemosyne but nothing changes. Any clue about the cause?

Thank you very much!

**Comment by jt6211** [comment]
It looks like the pymongo API changed.  I added version numbers to the
mnemosyne package list. To fix your install, do this

cd /opt/mnemosyne
source env/bin/activate

cat > /tmp/requirements.txt <<EOF
pymongo==2.7.2
gevent==1.0.1
bottle-mongodb==0.2.1
bottle-cork==0.6
git+https://github.com/defnull/bottle/
Beaker==1.6.4
WebTest==2.0.16
pycrypto==2.6.1
python-magic==0.4.6
nose==1.3.4
kumo==0.2
-e git+https://github.com/threatstream/hpfeeds/#egg=hpfeeds-dev
Sphinx==1.2.3
sphinxcontrib-httpdomain==1.3.0
EOF

pip install -r /tmp/requirements.txt
sudo supervisorctl restart mnemosyne


On Fri, Apr 10, 2015 at 9:17 AM, Ryuz3n <notifications@github.com> wrote:

> Hi!
>
> Just installed MHN but I'm unable to run mnemosyne, always getting: "*mnemosyne:
> ERROR (abnormal termination)*". I've tried both in Ubuntu 14.04 x64 and
> Ubuntu 12.04 x32 machines, but always getting the same result.
>
> *mnemosyne.err* shows:
>
> Traceback (most recent call last):
> File "runner.py", line 31, in
> from webapi import mnemowebapi
> File "/opt/mnemosyne/webapi/mnemowebapi.py", line 26, in
> from bottle.ext import mongo
> File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/bottle.py",
> line 1881, in load_module
> *import*(realname)
> File
> "/opt/mnemosyne/env/local/lib/python2.7/site-packages/bottle_mongo.py",
> line 3, in
> from pymongo import Connection
> ImportError: cannot import name Connection
>
> I've tried restarting MongoDB before trying to start mnemosyne but nothing
> changes. Any clue about the cause?
>
> Thank you very much!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/153>.
>



-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Ryuz3n** [comment]
Yes, it's working now. Thanks!

**Comment by polikarpio** [comment]
Not sure if I came to the right spot; but just installed MHN and i have same error as above but have a different error on the error log. 

> Traceback (most recent call last):
  File "runner.py", line 29, in <module>
    from normalizer.normalizer import Normalizer
  File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
    from modules import glastopf_files
  File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <module>
    import magic
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/magic.py", line 161,
in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
Traceback (most recent call last):
  File "runner.py", line 29, in <module>
    from normalizer.normalizer import Normalizer
  File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
    from modules import glastopf_files
  File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <module>
    import magic
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/magic.py", line 161,
in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
Traceback (most recent call last):
  File "runner.py", line 29, in <module>
    from normalizer.normalizer import Normalizer
  File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
    from modules import glastopf_files
  File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <module>
    import magic
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/magic.py", line 161,
in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
Traceback (most recent call last):

>
