### ISSUE TITLE
ImportError: No module named pymongo

### ISSUE THREAD

**Issue by syrion89** [threatstream/mhn#258]
When i run sudo ./install_honeymap.sh i got this error:

```
++ python -c 'import uuid;print str(uuid.uuid4()).replace("-","")'
+ SECRET=db13d571dc5f427fbfde340c1826e8a7
+ /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py geoloc db13d571dc5f427fbfde340c1826e8a7 geoloc.events amun.events,dionaea.connections,dionaea.capture,glastopf.events,beeswarm.hive,kippo.sessions,conpot.events,snort.alerts,kippo.alerts,wordpot.events,shockpot.events,p0f.events,suricata.events,elastichoney.events
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/add_user.py", line 2, in <module>
    import pymongo
ImportError: No module named pymongo
+ cat
+ cat
+ supervisorctl update
```

Pymongo is installed , i tried a lot of solutions found on web, but no one works for me.
Can you help me? Thanks!

**Comment by jt6211** [comment]
Can you run this and provide its output:

/opt/hpfeeds/env/bin/pip freeze



On Sun, Apr 10, 2016 at 5:13 PM, syrion89 <notifications@github.com> wrote:

> When i run sudo ./install_honeymap.sh i got this error:
>
> ++ python -c 'import uuid;print str(uuid.uuid4()).replace("-","")'
> + SECRET=db13d571dc5f427fbfde340c1826e8a7
> + /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py geoloc db13d571dc5f427fbfde340c1826e8a7 geoloc.events amun.events,dionaea.connections,dionaea.capture,glastopf.events,beeswarm.hive,kippo.sessions,conpot.events,snort.alerts,kippo.alerts,wordpot.events,shockpot.events,p0f.events,suricata.events,elastichoney.events
> Traceback (most recent call last):
>   File "/opt/hpfeeds/broker/add_user.py", line 2, in <module>
>     import pymongo
> ImportError: No module named pymongo
> + cat
> + cat
> + supervisorctl update
>
> Pymongo is installed , i tried a lot of solutions found on web, but no one
> works for me.
> Can you help me? Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/258>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by jingxa** [comment]
hello,can you help me ?i don't understand how to solve this problem,when i install mhn ,i can't install honeymap ,it always tell me that '/opt/honeymap/server/server' don't exist ?  And i try to   run fixed install_honemap.sh,it tells me that pymongo error ,i will be crazy ,can you help me ? sorry for my english

**Comment by jt6211** [comment]
What OS and version?

**Comment by jingxa** [comment]
yeah,thanks,i use ubuntu 14.04 in vmware,but i come from China,does it cause?  i  install mhn so that i have to buy a Foreign VPS, so i had finished it yesterday,but there is not any error. so i want to understand what i can do when i install mhn in my vmware. Thanks for your help!
