### ISSUE TITLE
"[Errno -2] Name or service not known" in /opt/hpfeeds/broker/add_user.py 

### ISSUE THREAD

**Issue by atgithub11** [threatstream/mhn#293]
Hi,

I am trying to deploy mhn on a CentOS 6.8 VM and running into the following error while running the install script. Script terminates once it encounters this error.

+ python /opt/hpfeeds/broker/add_user.py mnemosyne xxxxxxxxxxxxxxxxxxxxxxxxxx '' amun.events,conpot.events,thug.events,beeswarm.hive,dionaea.capture,dionaea.connections,thug.files,beeswarn.feeder,cuckoo.analysis,kippo.sessions,cowrie.sessions,glastopf.events,glastopf.files,mwbinary.dionaea.sensorunique,snort.alerts,wordpot.events,p0f.events,suricata.events,shockpot.events,elastichoney.events
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/add_user.py", line 29, in <module>
    res = client.hpfeeds.auth_key.update({"identifier": ident}, {"$set": rec}, upsert=True)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/collection.py", line 2242, in update
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 762, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno -2] Name or service not known

Mongo DB appears to be running fine and accepting connections on 27017

2016-07-18T15:00:45.781-0400 [initandlisten] MongoDB starting : pid=12025 port=27017 dbpath=/var/lib/mongo 64-bit host=Centos
2016-07-18T15:00:45.781-0400 [initandlisten] db version v2.6.12
2016-07-18T15:00:45.781-0400 [initandlisten] git version: d73c92b1c85703828b55c2916a5dd4ad46535f6a
2016-07-18T15:00:45.782-0400 [initandlisten] build info: Linux build5.ny.cbi.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 BOOST_LIB_VERSION=1_49
2016-07-18T15:00:45.782-0400 [initandlisten] allocator: tcmalloc
2016-07-18T15:00:45.782-0400 [initandlisten] options: { config: "/etc/mongod.conf", net: { bindIp: "127.0.0.1", port: 27017 }, processManagement: { fork: true, pidFilePath: "/var/run/mongodb/mongod.pid" }, storage: { dbPath: "/var/lib/mongo" }, systemLog: { destination: "file", logAppend: true, path: "/var/log/mongodb/mongod.log" } }
2016-07-18T15:00:45.869-0400 [initandlisten] journal dir=/var/lib/mongo/journal
2016-07-18T15:00:45.869-0400 [initandlisten] recover : no journal files present, no recovery needed
2016-07-18T15:00:45.961-0400 [initandlisten] waiting for connections on port 27017
2016-07-18T15:00:48.419-0400 [initandlisten] connection accepted from 127.0.0.1:48988 #1 (1 connection now open)
2016-07-18T15:01:45.954-0400 [clientcursormon] mem (MB) res:29 virt:456
2016-07-18T15:01:45.954-0400 [clientcursormon]  mapped (incl journal view):160
2016-07-18T15:01:45.954-0400 [clientcursormon]  connections:1

While checking the status, the only item listed is hpfeeds-broker.
supervisorctl status
hpfeeds-broker                   RUNNING   pid 19348, uptime 1:00:09

Thanks,

**Comment by jt6211** [comment]
What is the output of these commands?
```
sudo netstat -luntp | grep 27017

grep localhost /etc/hosts
```

**Comment by atgithub11** [comment]
Hi jt6211,

That was it.. Issue was the missing "localhost" under /etc/hosts
Here are the results:

netstat -luntp | grep 27017
tcp        0      0 127.0.0.1:27017             0.0.0.0:*                   LISTEN      12025/mongod

grep localhost /etc/hosts
#::1            localhost6.localdomain6 localhost6

Un-commented the entry and added "localhost". Re-ran the install and it finished without any issues.

Thanks for the quick response.

**Comment by muditagr** [comment]
Same issue, results of commnds : 
 sudo netstat -luntp | grep 27017
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      4219/mongod 

grep localhost /etc/hosts
127.0.0.1	localhost
::1     ip6-localhost ip6-loopback

**Comment by jt6211** [comment]
What is the output of this command?
```
ifconfig
```

You sure your loopback is configured to use `127.0.0.1`?
