### ISSUE TITLE
undefined symbol: sqlite3_stmt_readonly

### ISSUE THREAD

**Issue by wangyufeng0615** [threatstream/mhn#298]
I got this error when the install_mhnserver.sh is running, line 'python initdatabase.py'.

What should I do?

Thanks!

```
Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 5, in <module>
    create_clean_db()
  File "/opt/mhn/server/mhn/__init__.py", line 115, in create_clean_db
    db.create_all()
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 895, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 887, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 833, in get_engine
    return connector.get_engine()
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 499, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
**ImportError: /opt/mhn/env/lib/python2.7/site-packages/pysqlite2/_sqlite.so: undefined symbol: sqlite3_stmt_readonly**
```

**Comment by jt6211** [comment]
What OS and version?

**Comment by wangyufeng0615** [comment]
Ubuntu 10.10
I know this is too old but I have no more choice yet.

**Comment by wangyufeng0615** [comment]
Ok I've give up Ubuntu 10.10. Everyting is ok at Ubuntu 14.04.

And plz consider my 2 pull request, they are simple but I think is necessary.

**Comment by disunlike** [comment]
I've CentOs6 , the same question。
----
宝宝不开心了

**Comment by hanfeicode** [comment]
metoo.

[root@iZ25qx8tkgwZ apscheduler]# python withsql.py 
Traceback (most recent call last):
  File "withsql.py", line 10, in <module>
    'default': SQLAlchemyJobStore(url='sqlite://jobs.sqlite')
  File "/usr/local/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 49, in __init__
    self.engine = create_engine(url)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: /usr/local/lib/python2.7/site-packages/pysqlite2/_sqlite.so: undefined symbol: sqlite3_stmt_readonly


centos6.5 py2.7
