### ISSUE TITLE
install.sh broken on raspbian 8.0

### ISSUE THREAD

**Issue by roweryan** [threatstream/mhn#311]
When running install.sh on a Raspberry Pi, I get the error:

`W: Failed to fetch http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/Release  Unable to find expected entry '10gen/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)`

This is because there is no mongodb build for armhf from that repo.

Patch to fix it:

```
--- install_mongo.sh.ORIG   2016-08-30 18:53:45.362429093 +0000
+++ install_mongo.sh    2016-08-30 18:54:59.581811292 +0000
@@ -4,10 +4,7 @@
 set -x

 if [ -f /etc/debian_version ]; then
-    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
-    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
-    apt-get update
-    apt-get install -y mongodb-org
+    apt-get install -y mongodb

 elif [ -f /etc/redhat-release ]; then
     OS=RHEL

```

**Comment by roweryan** [comment]
honeymap requires go 1.4.2 from the official golang repo, but there is no official arm build for that version.

To fix honeymap:
```
# supervisorctl status
honeymap                         FATAL      can't find command '/opt/honeymap/server/server'
```

I used this patch:
```
# diff install_honeymap.sh.ORIG install_honeymap.sh
40a41,42
> cd /usr/local/
> 
43a46,50
>     wget https://storage.googleapis.com/golang/${GO_PACKAGE}
> elif [ "$(uname -m)" == "armv7l" ]; 
> then
>     GO_PACKAGE="go1.4.3.linux-armv7.tar.gz"
>     wget https://github.com/hypriot/golang-armbuilds/releases/download/v1.4.3/${GO_PACKAGE}
45a53
>     wget https://storage.googleapis.com/golang/${GO_PACKAGE}
48,49d55
< cd /usr/local/
< wget https://storage.googleapis.com/golang/${GO_PACKAGE}
```

Then restarted it:

```
# supervisorctl restart honeymap
# supervisorctl status honeymap
honeymap                         RUNNING    pid 17915, uptime 0:00:23
```

**Comment by roweryan** [comment]
To fix mnemosyne (not arm specific, but raspbian 8.0/jessie specific):

```
# supervisorctl status
mnemosyne                        FATAL      Exited too quickly (process log may have details)

# less /var/log/mhn/mnemosyne.err
NameError: name 'PROTOCOL_SSLv3' is not defined
Traceback (most recent call last):
  File "runner.py", line 21, in <module>
    gevent.monkey.patch_all()
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/monkey.py", line 185, in patch_all
    patch_socket(dns=dns, aggressive=aggressive)
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/monkey.py", line 124, in patch_socket
    from gevent import socket
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
```

Patch:

```
# diff -u /opt/mnemosyne/env/lib/python2.7/site-packages/gevent/ssl.py.ORIG /opt/mnemosyne/env/lib/python2.7/site-packages/gevent/ssl.py
--- /opt/mnemosyne/env/lib/python2.7/site-packages/gevent/ssl.py.ORIG	2016-08-30 20:17:02.449148860 +0000
+++ /opt/mnemosyne/env/lib/python2.7/site-packages/gevent/ssl.py	2016-08-30 20:17:13.719065067 +0000
@@ -383,7 +383,7 @@
                      ciphers=ciphers)

 
-def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
+def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv23, ca_certs=None):
     """Retrieve the certificate from the server at the specified address,
     and return it as a PEM-encoded string.
     If 'ca_certs' is specified, validate the server cert against it.
```

Restart:

```
# supervisorctl status mnemosyne
mnemosyne                        FATAL      Exited too quickly (process log may have details)
# supervisorctl restart mnemosyne
mnemosyne: ERROR (not running)
mnemosyne: started
```

**Comment by Udayasri1988** [comment]
This is worked for me I had **"mnemosyne   FATAL      Exited too quickly (process log may have details)"** error
>  get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
> +def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv23, ca_certs=None):
>      """Retrieve the certificate from the server at the specified address,
>      and return it as a PEM-encoded string.
>      If 'ca_certs' is specified, validate the server cert against it.
