### ISSUE TITLE
Kippo Not Sending Attacks

### ISSUE THREAD

**Issue by darksheer** [threatstream/mhn#343]
Kippo data is not being displayed in the MHN server. 

Setup the MHN server and a single Kippo pot instance.  The instance registers properly and is viewable in the Sensors tab, but shows not attacks occurring.  
When manually starting, with start.sh:

```
Loading dblog engine: hpfeeds
hpfeeds DBLogger start
hpfeeds client init broker XXX.XXX.XXX.XXX:10000, identifier XXXXXX
hpclient established
```

When conducting a test brute force against kippo, the following is logged in kippo.log

```
2016-12-04 09:49:46+0000 [HoneyPotTransport,112,66.22.198.99] connection lost
2016-12-04 09:49:46+0000 [HoneyPotTransport,112,66.22.198.99] publishing metadata to hpfeeds
2016-12-04 09:49:46+0000 [HoneyPotTransport,110,66.22.198.99] Remote SSH version: SSH-2.0-OpenSSH_7.1
2016-12-04 09:49:46+0000 [HoneyPotTransport,110,66.22.198.99] Disconnecting with error, code 3
	reason: couldn't match all kex parts
```

It appears that mnemosyne wont start:

```
supervisorctl status
geoloc                           RUNNING    pid 15378, uptime 2:01:40
honeymap                         RUNNING    pid 15377, uptime 2:01:40
hpfeeds-broker                   RUNNING    pid 29222, uptime 2:03:16
hpfeeds-logger-json              RUNNING    pid 16854, uptime 1:52:56
kibana                           RUNNING    pid 18104, uptime 1:52:03
logstash                         RUNNING    pid 18105, uptime 1:52:03
mhn-celery-beat                  RUNNING    pid 16697, uptime 1:53:28
mhn-celery-worker                RUNNING    pid 18137, uptime 1:52:03
mhn-collector                    RUNNING    pid 16700, uptime 1:53:28
mhn-uwsgi                        RUNNING    pid 16699, uptime 1:53:28
mnemosyne                        FATAL      Exited too quickly (process log may have details)
snort                            RUNNING    pid 31143, uptime 0:29:08
```
When manually restarting the service, the following is logged in /var/log/mhn/mnemosyne.err:

```
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/__init__.py", line 36, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in <module>
    import greenlet  # http://pypi.python.org/pypi/greenlet/
ImportError: /opt/mnemosyne/env/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/__init__.py", line 36, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in <module>
    import greenlet  # http://pypi.python.org/pypi/greenlet/
ImportError: /opt/mnemosyne/env/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/__init__.py", line 36, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in <module>
    import greenlet  # http://pypi.python.org/pypi/greenlet/
ImportError: /opt/mnemosyne/env/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
```

**Comment by darksheer** [comment]
Did find this article:

https://groups.google.com/forum/m/#!msg/modern-honey-network/pRXMGR1KYZU/KpHZVOKnCQAJ

**Comment by juju4** [comment]
kippo has issues with recent ssh client, see https://github.com/desaster/kippo/issues/194. have similar problem even with latest. check cowrie as alternative.

**Comment by hackdefendr** [comment]
I'm seeing the same issue on a fresh install on a vanilla Ubuntu 14 VM.  Kippo is running and I am seeing connections, but MHN is not recording the attacks.

Anyone have any other ideas?

**Comment by d1str0** [comment]
According to https://groups.google.com/forum/m/#!msg/modern-honey-network/pRXMGR1KYZU/KpHZVOKnCQAJ this has been resolved.
