### ISSUE TITLE
celery-worker consuming most of cpu?

### ISSUE THREAD

**Issue by juju4** [threatstream/mhn#370]
I have my mhn server on a basic vps (digitalocean) for now.
The main issue I have is celery eating almost all the cpu constantly

```
root@mhntop:~# supervisorctl status
geoloc                           RUNNING   pid 17677, uptime 5 days, 22:41:44
honeymap                         RUNNING   pid 17681, uptime 5 days, 22:41:44
hpfeeds-broker                   RUNNING   pid 18549, uptime 1:01:40
hpfeeds-logger-json              RUNNING   pid 17679, uptime 5 days, 22:41:44
mhn-celery-beat                  RUNNING   pid 17674, uptime 5 days, 22:41:44
mhn-celery-worker                RUNNING   pid 17676, uptime 5 days, 22:41:44
mhn-collector                    RUNNING   pid 17680, uptime 5 days, 22:41:44
mhn-uwsgi                        RUNNING   pid 17678, uptime 5 days, 22:41:44
mnemosyne                        RUNNING   pid 17673, uptime 5 days, 22:41:44
root@mhntop:~# ps axu |grep celery
_mhn     17674  0.0  0.7 145380  3920 ?        S    Feb12   0:09 /var/_mhn/mhn/env/bin/python2 /var/_mhn/mhn/env/bin/celery beat -A mhn.tasks --loglevel=INFO --pidfile=/var/run/mhn/mhn-celery-beat.pid
_mhn     17676  0.1  1.7 140748  8724 ?        SN   Feb12  10:57 /var/_mhn/mhn/env/bin/python2 /var/_mhn/mhn/env/bin/celery worker -A mhn.tasks --loglevel=INFO
_mhn     23243 90.6 30.7 374660 153748 ?       RN   Feb17 1070:55 /var/_mhn/mhn/env/bin/python2 /var/_mhn/mhn/env/bin/celery worker -A mhn.tasks --loglevel=INFO
```

From the log, it seems it reimport rules (snort?) every 30-40min
```
root@mhntop:~# grep -rin "Finished Importing" /var/log/mhn/mhn-celery-worker.log.1 | tail -10
10840:[2017-02-17 19:52:04,571: WARNING/Worker-24] Finished Importing 20762 rules.  Committing data
10890:[2017-02-17 20:36:06,992: WARNING/Worker-24] Finished Importing 20762 rules.  Committing data
10940:[2017-02-17 21:20:43,586: WARNING/Worker-24] Finished Importing 20762 rules.  Committing data
10990:[2017-02-17 22:01:49,052: WARNING/Worker-24] Finished Importing 20762 rules.  Committing data
11040:[2017-02-17 22:44:31,882: WARNING/Worker-24] Finished Importing 20798 rules.  Committing data
11090:[2017-02-17 23:25:06,546: WARNING/Worker-24] Finished Importing 20798 rules.  Committing data
11140:[2017-02-18 00:04:51,420: WARNING/Worker-24] Finished Importing 20798 rules.  Committing data
11190:[2017-02-18 00:44:37,698: WARNING/Worker-24] Finished Importing 20798 rules.  Committing data
11240:[2017-02-18 01:25:25,320: WARNING/Worker-24] Finished Importing 20798 rules.  Committing data
11290:[2017-02-18 02:04:31,975: WARNING/Worker-24] Finished Importing 20798 rules.  Committing data
```

is there a way to change frequency of import? other way to reduce load on the system?
or any plan to do incremental rule update?

Thanks

I already edit supervisor config to nice+ionice the process but 
```
# more /etc/supervisor/conf.d/mhn-celery-worker.conf 
## /etc/supervisor/conf.d/mhn-celery-worker.conf
[program:mhn-celery-worker]
command=/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /var/_mhn/mhn/env/bin/celery worker -A mhn.tasks --loglevel=INFO
directory=/var/_mhn/mhn/server
user=_mhn
stdout_logfile=/var/log/mhn/mhn-celery-worker.log
#stderr_logfile=/var/log/mhn/mhn-celery-worker.err
redirect_stderr=true
autostart=true
autorestart=true
startsecs=10
#user=www-data
```

RAM is usually loaded in 60-80% (512M)

Note: I reviewed hardware recommendations (https://github.com/threatstream/mhn/wiki/Hardware-Recommendations)

**Comment by MNFaust** [comment]
I am having this same issue. I upgraded my Droplet and rebooted and boom 99.8% CPU for about the last hour... Can not figure out why the celery worker is working this hard.

**Comment by Dragolf** [comment]
I also have this problem, and because of this problem, the map is not showing attacks in real-time, after reboot of the server it worked normal, but after some time it again consumes 98-99% CPU, i've restarted the server again, and i'll monitor it to see when the process will consume CPU again, i have suspicions that Dionaea installed with default configs is overloading the MHN server with logs, becaous when i do a test scan of my sensor it looks like the attacks are showed on MHN dashboard or in attacks with great delay, could that be a reason to this issue?

My HW is 
4GB RAM
dual core processor
and 1TB drive

**Comment by jafo65** [comment]
Seems it is unable to find a database file. Permissions are correct on files. It could be a PATH issue viz-a-vi database file?


[2018-01-03 23:47:32,812: INFO/Worker-6] Bulk importing 19659 rules.
[2018-01-03 23:47:35,390: ERROR/MainProcess] Task mhn.tasks.rules.fetch_sources[5431301f-c481-42b7-9bf6-ea1ba54f0cb9] raised unexpected: OperationalError('(pysqlite2.dbapi2.OperationalError) unable to open database file',)
Traceback (most recent call last):
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/mhn/server/mhn/tasks/__init__.py", line 13, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/mhn/server/mhn/tasks/rules.py", line 82, in fetch_sources
    Rule.bulk_import(rules)
  File "/opt/mhn/server/mhn/api/models.py", line 191, in bulk_import
    update({'is_active': False}, False)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3345, in update
    update_op.exec_()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1177, in exec_
    self._do_pre()
  File "<string>", line 1, in <lambda>
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1215, in _do_pre
    session._autoflush()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1422, in _autoflush
    util.raise_from_cause(e)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1412, in _autoflush
    self.flush()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) unable to open database file [SQL: u'INSERT INTO rules (message, classtype, sid, rev, date, rule_format, is_active, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (u'ET INFO PhishMe.com Phishing Landing Exercise', u'trojan-activity', 2022730, 2, '2018-01-04 04:47:35.321424', u'alert tcp $EXTERNAL_NET $HTTP_PORTS -> $HOME_NET any ({msg}; flow:to_client,established; content:"200"; http_stat_code; content:"_phishme.com_sessio ... (146 characters truncated) ...  metadata:attack_target Client_Endpoint, deployment Perimeter, tag Phishing, signature_severity Major, created_at 2016_04_13, updated_at 2017_12_29;)', 1, None)]
[2018-01-03 23:47:35,397: INFO/MainProcess] Received task: mhn.tasks.rules.fetch_sources[4687a6ee-1215-4eeb-901a-aa3221f92597]
[2018-01-03 23:47:35,403: INFO/Worker-6] Fetching sources from 1 sources.
[2018-01-03 23:47:35,406: INFO/Worker-6] Downloading from "http://rules.emergingthreats.net/open/snort-2.9.0/emerging.rules.tar.gz".
[2018-01-03 23:47:35,410: INFO/Worker-6] Starting new HTTP connection (1): rules.emergingthreats.net

**Comment by kyle-schleich** [comment]
Was anything else found about this?

**Comment by phage-nz** [comment]
Ran into this with a fresh build yesterday. Try change the owner of /var/log/mhn to www-data. chmod mask of the folder and files shouldn't need to change. The www-data user looks to be trying to roll some of the log files but fails to, which for some reason results in continual pulls of the ET ruleset.
