### ISSUE TITLE
Error on Installation in Kali

### ISSUE THREAD

**Issue by gauravdwivedi10** [threatstream/mhn#384]
Installing collected packages: ipaddress, idna, asn1crypto, enum34, cryptography, pyopenssl

Successfully installed asn1crypto-0.22.0 cryptography-1.8.1 enum34-1.1.6 idna-2.5 ipaddress-1.0.18 pyopenssl-0.14
+ pip install pymongo
Traceback (most recent call last):
  File "/opt/hpfeeds/env/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/opt/hpfeeds/env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/opt/hpfeeds/env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/opt/hpfeeds/env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/opt/hpfeeds/env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/opt/hpfeeds/env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/opt/hpfeeds/env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/opt/hpfeeds/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

..................................................................................................................................
Please Let me know how to rectify the error?

**Comment by NitescuLucian** [comment]
Could you try deleting the openssl python lib and reinstalling it?
```
$ sudo rm -rf /usr/local/lib/python2.7/dist-packages/OpenSSL/
$ sudo apt install --reinstall python-openssl
```

**Comment by d1str0** [comment]
For further support, please send a detailed email to the google group: https://groups.google.com/forum/#!forum/modern-honey-network
