### ISSUE TITLE
initdatabase.py still failing

### ISSUE THREAD

**Issue by TedLeRoy** [threatstream/mhn#385]
Issue #351 is still an issue or has come back as an issue. I've tried on both CentOS 6.8 (oldest default build on DigitalOcean) and Ubuntu 14.04.5. Both were clean DigitalOcean builds. I verified that the Python version on Ubuntu was 2.7.6 and it still failed. Capture from the CentOS server below. It was not running Python 2.7.6, but 2.6.6, but the error is the same as with Ubuntu which was running 2.7.6:

+ echo ===========================================================
===========================================================
+ echo '  MHN Configuration'
  MHN Configuration
+ echo ===========================================================
===========================================================
+ python generateconfig.py
config.py already exists
+ echo -e '\nInitializing database, please be patient. This can take several minutes'

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 5, in <module>
    create_clean_db()
  File "/opt/mhn/server/mhn/__init__.py", line 123, in create_clean_db
    db.session.flush()
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
    self._flush(objects)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
    flush_context.execute()
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1394, in _handle_dbapi_exception
    exc_info
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/mhn/env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (pysqlite2.dbapi2.IntegrityError) UNIQUE constraint failed: role.name [SQL: u'INSERT INTO role (name, description) VALUES (?, ?)'] [parameters: ('admin', '')]

**Comment by RyanLindfield** [comment]
I've been struggling with this today as well, the installation simply fails, Ubuntu 16, 14 and Cento OS all fail here.

**Comment by Philelis** [comment]
Delete mhn.db and try again ;)

**Comment by 0x7fff9** [comment]
Hi! me and Juju cover that on #383.
check that and comment there if any issues. we can help.

cheers.

**Comment by TedLeRoy** [comment]
Thanks RyanLindfield, Philelis, and 0x7fff9. I used a combination of the steps found in #383, and Philelis' comment. I tried editing the models.py file, then re-ran. That didn't work, so I removed the database and re-ran and it works. I'll do some experimenting to see if it was the file edits, removing the db, or both that were needed on a clean Ubuntu 14 build and post again. 

If the file edits are needed, I hope we can do a pull request, make the changes, and commit, or have someone with access do that.

Great work by 0x7fff9 and Juju, and thanks to you too Philelis!

**Comment by 0x7fff9** [comment]
yeah, the file edits are indeed required.
basically if you run the install.py without editing the models.py you will go untill 7500 imported rules which is already past user conf import on DB leading to an after edit error on DB import due to lack of uniqueness.

If you on 1st run edit the models.py you won't experience errors on ubuntu 14.4/16.4 and CentOS 6.7 only on ELK, but that's other story :)

**Comment by TedLeRoy** [comment]
Thanks 0x7fff9. How do we get the updates rolled into the code base, if you know?

**Comment by 0x7fff9** [comment]
need to make a pull req.
I'll make one tonight.

**Comment by TedLeRoy** [comment]
Very cool. Thanks 0x7fff9. I'm very interested in how you and Juju figured these things out. I'm glad you tackled it.

**Comment by TedLeRoy** [comment]
It looks like you haven't had a chance to do the pull request to integrate the changes. Here are the steps all in one place in the mean-time:

Edit models.py as follows:

# Your install directory may be different. This is for Ubuntu:
cd /opt/mhn/server/mhn/api/

# Make a copy of the original file so you can restore it if needed:
cp models.py models.py.orig

# Add the following to the beginning of the file:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

# Make the following change to the file:
# Change:
ref.text = r
# to
ref.text = r.decode('utf-8')

# Remove man.db
# Move to the right directory:
cd /opt/mhn/server/

# Copy mhn.db to home directory in case it is needed:
cp mhn.db ~/

# Remove mhn.cb
rm man.db

Rerun ./install.sh
cd /opt/mhn
./install.sh

You should be set!

**Comment by TedLeRoy** [comment]
0x7fff9, It looks like you've submitted the pull request. I hope someone commits your change soon.

**Comment by Philelis** [comment]
@0x7fff9  For your problem with Elk: I will change the install script that a complete install in Ubuntu and CentOS 7 will work. And I will use Elastic with Version 5 not 4. I have a version, but that only works for CentOS 7 so I have to do some Checks which System is used.

**Comment by jaydub1000** [comment]
Awesome. Thank you. This did fix my issue with the install. But I'm still not getting a log in on the web interface.
