### ISSUE TITLE
update and insert rule fail

### ISSUE THREAD

**Issue by dpicollege** [threatstream/mhn#394]
Hello guys are your rules update every 24h and you can see in rule section of interface?

how can slove this problem/
File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) unable to open database file [SQL: u'INSERT INTO rules (message, classtype, sid, rev, date, rule_format, is_active, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('ET CURRENT_EVENTS DRIVEBY PDF Containing Subform with JavaScript', 'attempted-user', 2014154, 4,

**Comment by Philelis** [comment]
Please take a look at [#364#issuecomment-295588319](https://github.com/threatstream/mhn/pull/364#issuecomment-295588319)

**Comment by 0x7fff9** [comment]
Hi. indeed the server should update every 12 hrs.
can you post the latest full attempt from `mhn-celery-worker.err` I suspect there is a permission denied prior to that import error.

cheers,
Guido.

**Comment by dpicollege** [comment]
thanks @0x7fff9  to replay me hear is two years and i couldn't solve such this problem here is my log

[2017-04-22 21:59:00,053: INFO/MainProcess] Received task: mhn.tasks.rules.fetch_sources[341bcf79-ec6a-4ff5-bc9c-6629cdf8c134]  
[2017-04-22 21:59:00,058: WARNING/PoolWorker-8] Traceback (most recent call last):
[2017-04-22 21:59:00,058: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 21:59:00,058: WARNING/PoolWorker-8] self.doRollover()
[2017-04-22 21:59:00,059: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 21:59:00,059: WARNING/PoolWorker-8] os.rename(self.baseFilename, dfn)
[2017-04-22 21:59:00,059: WARNING/PoolWorker-8] OSError: [Errno 13] Permission denied
[2017-04-22 21:59:00,059: WARNING/PoolWorker-8] Logged from file rules.py, line 31
[2017-04-22 21:59:00,060: WARNING/PoolWorker-8] Traceback (most recent call last):
[2017-04-22 21:59:00,060: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 21:59:00,060: WARNING/PoolWorker-8] self.doRollover()
[2017-04-22 21:59:00,061: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 21:59:00,061: WARNING/PoolWorker-8] os.rename(self.baseFilename, dfn)
[2017-04-22 21:59:00,061: WARNING/PoolWorker-8] OSError: [Errno 13] Permission denied
[2017-04-22 21:59:00,061: WARNING/PoolWorker-8] Logged from file rules.py, line 35
[2017-04-22 21:59:00,390: WARNING/PoolWorker-6] Imported 9500 rules so far...
[2017-04-22 21:59:01,989: WARNING/PoolWorker-6] Imported 10000 rules so far...
[2017-04-22 21:59:03,781: WARNING/PoolWorker-6] Imported 10500 rules so far...
[2017-04-22 21:59:05,377: WARNING/PoolWorker-6] Imported 11000 rules so far...
[2017-04-22 21:59:07,031: WARNING/PoolWorker-6] Imported 11500 rules so far...
[2017-04-22 21:59:08,636: WARNING/PoolWorker-6] Imported 12000 rules so far...
[2017-04-22 21:59:10,318: WARNING/PoolWorker-6] Imported 12500 rules so far...
[2017-04-22 21:59:11,923: WARNING/PoolWorker-6] Imported 13000 rules so far...
[2017-04-22 21:59:13,595: WARNING/PoolWorker-6] Imported 13500 rules so far...
[2017-04-22 21:59:15,365: WARNING/PoolWorker-6] Imported 14000 rules so far...
[2017-04-22 21:59:17,017: WARNING/PoolWorker-6] Imported 14500 rules so far...
[2017-04-22 21:59:18,623: WARNING/PoolWorker-6] Imported 15000 rules so far...
[2017-04-22 21:59:20,258: WARNING/PoolWorker-6] Imported 15500 rules so far...
[2017-04-22 21:59:21,842: WARNING/PoolWorker-6] Imported 16000 rules so far...
[2017-04-22 21:59:23,526: WARNING/PoolWorker-6] Imported 16500 rules so far...
[2017-04-22 21:59:25,175: WARNING/PoolWorker-6] Imported 17000 rules so far...
[2017-04-22 21:59:26,794: WARNING/PoolWorker-6] Imported 17500 rules so far...
[2017-04-22 21:59:28,409: WARNING/PoolWorker-6] Imported 18000 rules so far...
[2017-04-22 21:59:29,731: WARNING/PoolWorker-8] Traceback (most recent call last):
[2017-04-22 21:59:29,731: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 21:59:29,731: WARNING/PoolWorker-8] self.doRollover()
[2017-04-22 21:59:29,731: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 21:59:29,732: WARNING/PoolWorker-8] os.rename(self.baseFilename, dfn)
[2017-04-22 21:59:29,732: WARNING/PoolWorker-8] OSError: [Errno 13] Permission denied
[2017-04-22 21:59:29,732: WARNING/PoolWorker-8] Logged from file rules.py, line 76
[2017-04-22 21:59:30,089: WARNING/PoolWorker-6] Imported 18500 rules so far...
[2017-04-22 21:59:31,415: WARNING/PoolWorker-8] Imported 500 rules so far...
[2017-04-22 21:59:31,747: WARNING/PoolWorker-6] Imported 19000 rules so far...
[2017-04-22 21:59:33,054: WARNING/PoolWorker-8] Imported 1000 rules so far...
[2017-04-22 21:59:33,402: WARNING/PoolWorker-6] Imported 19500 rules so far...
[2017-04-22 21:59:34,700: WARNING/PoolWorker-8] Imported 1500 rules so far...
[2017-04-22 21:59:35,034: WARNING/PoolWorker-6] Imported 20000 rules so far...
[2017-04-22 21:59:35,736: WARNING/PoolWorker-6] Finished Importing 20194 rules.  Committing data
[2017-04-22 21:59:35,737: WARNING/PoolWorker-6] Traceback (most recent call last):
[2017-04-22 21:59:35,737: WARNING/PoolWorker-6] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 21:59:35,737: WARNING/PoolWorker-6] self.doRollover()
[2017-04-22 21:59:35,738: WARNING/PoolWorker-6] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 21:59:35,738: WARNING/PoolWorker-6] os.rename(self.baseFilename, dfn)
[2017-04-22 21:59:35,738: WARNING/PoolWorker-6] OSError: [Errno 13] Permission denied
[2017-04-22 21:59:35,738: WARNING/PoolWorker-6] Logged from file rules.py, line 19
[2017-04-22 21:59:36,345: WARNING/PoolWorker-8] Imported 2000 rules so far...
[2017-04-22 21:59:38,067: WARNING/PoolWorker-8] Imported 2500 rules so far...
[2017-04-22 21:59:38,316: WARNING/PoolWorker-7] Traceback (most recent call last):
[2017-04-22 21:59:38,316: WARNING/PoolWorker-7] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 21:59:38,317: WARNING/PoolWorker-7] self.doRollover()
[2017-04-22 21:59:38,317: WARNING/PoolWorker-7] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 21:59:38,317: WARNING/PoolWorker-7] os.rename(self.baseFilename, dfn)
[2017-04-22 21:59:38,317: WARNING/PoolWorker-7] OSError: [Errno 13] Permission denied
[2017-04-22 21:59:38,317: WARNING/PoolWorker-7] Logged from file rules.py, line 25
[2017-04-22 21:59:38,336: INFO/PoolWorker-7] Task mhn.tasks.rules.fetch_sources[3d77bba0-b76b-40c4-bb7a-35cc32a0e99c] succeeded in 218.28198467s: None
[2017-04-22 21:59:39,620: WARNING/PoolWorker-8] Imported 3000 rules so far...
[2017-04-22 21:59:41,168: WARNING/PoolWorker-8] Imported 3500 rules so far...
[2017-04-22 21:59:42,739: WARNING/PoolWorker-8] Imported 4000 rules so far...
[2017-04-22 21:59:44,454: WARNING/PoolWorker-8] Imported 4500 rules so far...
[2017-04-22 21:59:46,238: WARNING/PoolWorker-8] Imported 5000 rules so far...
[2017-04-22 21:59:47,904: WARNING/PoolWorker-8] Imported 5500 rules so far...
[2017-04-22 21:59:49,502: WARNING/PoolWorker-8] Imported 6000 rules so far...
[2017-04-22 21:59:51,123: WARNING/PoolWorker-8] Imported 6500 rules so far...
[2017-04-22 21:59:52,678: WARNING/PoolWorker-8] Imported 7000 rules so far...
[2017-04-22 21:59:54,285: WARNING/PoolWorker-8] Imported 7500 rules so far...
[2017-04-22 21:59:55,903: WARNING/PoolWorker-8] Imported 8000 rules so far...
[2017-04-22 21:59:57,650: WARNING/PoolWorker-8] Imported 8500 rules so far...
[2017-04-22 21:59:59,359: WARNING/PoolWorker-8] Imported 9000 rules so far...
[2017-04-22 22:00:00,929: WARNING/PoolWorker-8] Imported 9500 rules so far...
[2017-04-22 22:00:03,022: WARNING/PoolWorker-8] Imported 10000 rules so far...
[2017-04-22 22:00:05,028: WARNING/PoolWorker-8] Imported 10500 rules so far...
[2017-04-22 22:00:06,564: WARNING/PoolWorker-8] Imported 11000 rules so far...
[2017-04-22 22:00:08,124: WARNING/PoolWorker-8] Imported 11500 rules so far...
[2017-04-22 22:00:09,740: WARNING/PoolWorker-8] Imported 12000 rules so far...
[2017-04-22 22:00:11,365: WARNING/PoolWorker-8] Imported 12500 rules so far...
[2017-04-22 22:00:12,942: WARNING/PoolWorker-8] Imported 13000 rules so far...
[2017-04-22 22:00:14,598: WARNING/PoolWorker-8] Imported 13500 rules so far...
[2017-04-22 22:00:16,170: WARNING/PoolWorker-8] Imported 14000 rules so far...
[2017-04-22 22:00:17,803: WARNING/PoolWorker-8] Imported 14500 rules so far...
[2017-04-22 22:00:19,632: WARNING/PoolWorker-8] Imported 15000 rules so far...
[2017-04-22 22:00:21,274: WARNING/PoolWorker-8] Imported 15500 rules so far...
[2017-04-22 22:00:22,842: WARNING/PoolWorker-8] Imported 16000 rules so far...
[2017-04-22 22:00:24,577: WARNING/PoolWorker-8] Imported 16500 rules so far...
[2017-04-22 22:00:26,273: WARNING/PoolWorker-8] Imported 17000 rules so far...
[2017-04-22 22:00:28,026: WARNING/PoolWorker-8] Imported 17500 rules so far...
[2017-04-22 22:00:29,708: WARNING/PoolWorker-8] Imported 18000 rules so far...
[2017-04-22 22:00:31,317: WARNING/PoolWorker-8] Imported 18500 rules so far...
[2017-04-22 22:00:32,848: WARNING/PoolWorker-8] Imported 19000 rules so far...
[2017-04-22 22:00:34,400: WARNING/PoolWorker-8] Imported 19500 rules so far...
[2017-04-22 22:00:35,935: WARNING/PoolWorker-8] Imported 20000 rules so far...
[2017-04-22 22:00:36,605: WARNING/PoolWorker-8] Finished Importing 20194 rules.  Committing data
[2017-04-22 22:00:36,606: WARNING/PoolWorker-8] Traceback (most recent call last):
[2017-04-22 22:00:36,606: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 22:00:36,606: WARNING/PoolWorker-8] self.doRollover()
[2017-04-22 22:00:36,606: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 22:00:36,606: WARNING/PoolWorker-8] os.rename(self.baseFilename, dfn)
[2017-04-22 22:00:36,606: WARNING/PoolWorker-8] OSError: [Errno 13] Permission denied
[2017-04-22 22:00:36,606: WARNING/PoolWorker-8] Logged from file rules.py, line 19
[2017-04-22 22:00:40,419: WARNING/PoolWorker-3] Traceback (most recent call last):
[2017-04-22 22:00:40,419: WARNING/PoolWorker-3] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 22:00:40,419: WARNING/PoolWorker-3] self.doRollover()
[2017-04-22 22:00:40,419: WARNING/PoolWorker-3] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 22:00:40,419: WARNING/PoolWorker-3] os.rename(self.baseFilename, dfn)
[2017-04-22 22:00:40,419: WARNING/PoolWorker-3] OSError: [Errno 13] Permission denied
[2017-04-22 22:00:40,420: WARNING/PoolWorker-3] Logged from file rules.py, line 25
[2017-04-22 22:00:40,439: INFO/PoolWorker-3] Task mhn.tasks.rules.fetch_sources[d5d205b0-1243-451f-8398-d218c06b5633] succeeded in 220.431212284s: None
[2017-04-22 22:01:35,792: WARNING/PoolWorker-6] Traceback (most recent call last):
[2017-04-22 22:01:35,793: WARNING/PoolWorker-6] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 22:01:35,793: WARNING/PoolWorker-6] self.doRollover()
[2017-04-22 22:01:35,793: WARNING/PoolWorker-6] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 22:01:35,793: WARNING/PoolWorker-6] os.rename(self.baseFilename, dfn)
[2017-04-22 22:01:35,793: WARNING/PoolWorker-6] OSError: [Errno 13] Permission denied
[2017-04-22 22:01:35,793: WARNING/PoolWorker-6] Logged from file rules.py, line 25
[2017-04-22 22:01:35,811: INFO/PoolWorker-6] Task mhn.tasks.rules.fetch_sources[63b3ec4b-9b17-4fcd-88e1-74c0246d8f80] succeeded in 215.805322042s: None
[2017-04-22 22:02:32,143: WARNING/PoolWorker-8] Traceback (most recent call last):
[2017-04-22 22:02:32,143: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
[2017-04-22 22:02:32,144: WARNING/PoolWorker-8] self.doRollover()
[2017-04-22 22:02:32,144: WARNING/PoolWorker-8] File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
[2017-04-22 22:02:32,144: WARNING/PoolWorker-8] os.rename(self.baseFilename, dfn)
[2017-04-22 22:02:32,144: WARNING/PoolWorker-8] OSError: [Errno 13] Permission denied
[2017-04-22 22:02:32,144: WARNING/PoolWorker-8] Logged from file rules.py, line 25
[2017-04-22 22:02:32,162: INFO/PoolWorker-8] Task mhn.tasks.rules.fetch_sources[341bcf79-ec6a-4ff5-bc9c-6629cdf8c134] succeeded in 212.107203498s: None

**Comment by d1str0** [comment]
Is this still an issue?

**Comment by dpicollege** [comment]
yes, it's not working sometimes or we encounter with hich cpu load of mhn-celery-worker.
