### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by royikle** [threatstream/mhn#412]
Hi everyone,
I had installed MHN many times.
Always clone the same VM and install.
It's already like a SOP.
Today suddenly get a problem when I install the new MHN.
I try to install six .
```
sudo easy_install six
sudo pip install six
sudo apt-get install python-six
```
But still have the same question.
Did somebody have the same problem?

Here is the log.

    Copying pycparser.egg-info to /opt/hpfeeds/env/lib/python2.7/site-packages/pycparser-2.17-py2.7.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c25IY4/pycparser/setup.py", line 54, in <module>
        cmdclass={'install': install, 'sdist': sdist},
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-c25IY4/pycparser/setup.py", line 20, in run
        _install.run(self)
      File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 613, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/setuptools/command/install_scripts.py", line 17, in run
        import setuptools.command.easy_install as ei
      File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 49, in <module>
        from setuptools.py27compat import rmtree_safe
      File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/setuptools/py27compat.py", line 7, in <module>
        import six
    ImportError: No module named six
    
    ----------------------------------------
Command "/opt/hpfeeds/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c25IY4/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-WEFldR-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/hpfeeds/env/include/site/python2.7/pycparser" failed with error code 1 in /tmp/pip-build-c25IY4/pycparser/

**Comment by royikle** [comment]
I try the same install step today and nothing bug happen.
It's really make me confuse.
I'll close this case although I don't know how to solve this problem.
