### ISSUE TITLE
As usual, epic issues

### ISSUE THREAD

**Issue by Keldo** [threatstream/mhn#432]
Ubuntu 16 - Celery-Worker ERROR, hpfeeds-broker ERROR
Centos 6 - Far too many to list
Ubuntu 14 Same as Ubuntu 16

I have tried all of the trouble shooting steps, nothing works, server is currently Ubuntu 14 (although I hate using Ubuntu and prefer Debian or CentOS).

**Comment by Keldo** [comment]
hpfeeds-broker issue
`
cat hpfeeds-broker.err
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
`

**Comment by JBAnderson** [comment]
Ubunutu 16 is specifically mentioned in the docs as not being compatible so you aren't going to get far there. As far as the issue on Ubuntu 14, I wrote up how I got mine working here: 

http://www.attacusatlas.com/how-to-set-up-dionaea-honeypot-with-modern-honey-network-and-slack-alerts/

Hope that helps!

**Comment by Keldo** [comment]
Even after following your example on Ubuntu 14
`
cat hpfeeds-broker.err
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

`

**Comment by JBAnderson** [comment]
How is the error showing on the front end? What's not working?

**Comment by Keldo** [comment]
There are no errors on the front end but hpfeeds_broker is showing FATAL, when I check the error log, that's what I get, I had this running on Ubuntu 14 before and had no issues, now I have this

**Comment by JBAnderson** [comment]
I'll check my logs later tonight and see if I'm getting the same

**Comment by Keldo** [comment]
/opt/hpfeeds/env/bin/python -m pip install --upgrade pyopenssl
Updated pyopenssl and now everything is running.
