### ISSUE TITLE
Mnemosyne Fatal error

### ISSUE THREAD

**Issue by dimasdanang** [threatstream/mhn#434]
hi guys, can you help me ?
in log mnemosyne.err 
Traceback (most recent call last):
  File "runner.py", line 29, in <module>
    from normalizer.normalizer import Normalizer
  File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
    from modules import glastopf_files
  File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <module>
    import magic
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/magic.py", line 161, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

what should i do guys ? thank

**Comment by bflew** [comment]
I think its broken

**Comment by bflew** [comment]
to resolve I destroyed my VPS and recreated, working fine first install, if you reboot your server it messes up so once its up and running don't reboot

**Comment by d1str0** [comment]
Please try install with the latest code.
