### ISSUE TITLE
Mnemosyne error

### ISSUE THREAD

**Issue by g6a** [threatstream/mhn#443]
Hi ,
we found the following log in mnemosyne.err for a long time,
before last week, it just a error message, and the mnemosyne still works...
but from last week, sometime mnemosyne will hang and stop doing normalize,
we need to restart mnemosyne to make it work again.
what is the reason for this error message??
Thanks.
=== error message ===========
2017-08-07 17:26:13,407 (pyhpfeeds) connecting to localhost:10000
Traceback (most recent call last):
  File "/opt/mnemosyne/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/socket.py", line 342, in connect
    raise error(err, strerror(err))
error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/mnemosyne/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/socket.py", line 349, in connect
    raise error(result, strerror(result))
error: [Errno 99] Cannot assign requested address
2017-08-07 17:26:13,409 (pyhpfeeds) FeedException while connecting: Could not connect to broker [localhost].
2017-08-07 17:26:33,420 (pyhpfeeds) connecting to localhost:10000
Traceback (most recent call last):
  File "/opt/mnemosyne/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/socket.py", line 342, in connect
    raise error(err, strerror(err))
error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/mnemosyne/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/socket.py", line 349, in connect
    raise error(result, strerror(result))
error: [Errno 99] Cannot assign requested address
2017-08-07 17:26:33,422 (pyhpfeeds) FeedException while connecting: Could not connect to broker [localhost].

**Comment by d1str0** [comment]
Can you confirm all the services are running if you execute 'sudo supervisorctl status' ?

There's a chance you need to update pyopenssl. See issue #441

**Comment by g6a** [comment]
Hi,
all the service are running ...
and I forgot when do I update pyopenssl,
but I didn't see any error message like this for a long time.

Thanks



2017-10-03 11:23 GMT+08:00 Brady Sullivan <notifications@github.com>:

**Comment by d1str0** [comment]
Did you try and update pyopenssl? Did that solve your issue?

**Comment by d1str0** [comment]
Are you still having issues?

**Comment by Xopid** [comment]
if u have problem installing mnemosyne, try to edit requirements.txt in /opt/mnemosyne then change the gevent version to 1.3.5.
after that go to /opt/mhn/scripts then edit the install_mnemosyne.sh with nano and comment the mkdir,rm -rf and git clone then change the chmod to 777.
then try to run the install.sh again
