### ISSUE TITLE
hp-feedsbroker will not start

### ISSUE THREAD

**Issue by m1357** [threatstream/mhn#458]
tried restarting from supervisorctl but just fails

from hpfeeds-broker.err

AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by d1str0** [comment]
Please see issue #441 

Newest install scripts should not exhibit this error.
