### ISSUE TITLE
MHN Install fails on Ubuntu 14

### ISSUE THREAD

**Issue by royikle** [threatstream/mhn#484]
Hi everyone
I get an install problem when I install hpfeeds-logger.
I see the fix issue about:
https://github.com/threatstream/mhn/commit/4d57d6d4285f6c39b0d970540a8bc10e8b0c12e8
Those three file in my VM is already been `pip install hpfeeds-logger==0.0.7.3`
Thanks for @d1str0 .
But I still get error.
Is someone have another way to fix this problem?
Best regards.

```
Collecting hpfeeds-logger==0.0.5a (from -r server/requirements.txt (line 20))
  Downloading hpfeeds-logger-0.0.5a.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oGSYDd/hpfeeds-logger/setup.py", line 16, in <module>
        use_setuptools()
      File "ez_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "ez_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "ez_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oGSYDd/hpfeeds-logger/

```

**Comment by tommytee89** [comment]
update your requirements.txt in /server... it should read hpfeeds-logger==0.0.7.3

**Comment by d1str0** [comment]
Did you 'git pull' the latest code?

**Comment by d1str0** [comment]
@tommytee89 is correct. This slipped through the cracks with the last two PRs...

**Comment by royikle** [comment]
I fix it.
Thanks for @tommytee89 @d1str0 .
So if I use `sudo git clone https://github.com/threatstream/mhn.git` to download install file now.
Should I need to use `git pull` ?

**Comment by manipulator01** [comment]
thanks for the fix! Much appreciated.
