### ISSUE TITLE
Celery worker error

### ISSUE THREAD

**Issue by jjjan** [threatstream/mhn#494]
Hello
i facing this error when celery want to import fetched rules.

[2017-11-05 16:29:47,037: WARNING/Worker-15] Imported 12000 rules so far...
[2017-11-05 16:29:47,585: ERROR/MainProcess] Task mhn.tasks.rules.fetch_sources[b44aabc8-5c76-47db-a6a2-1ecf289b0256] raised unexpected: OperationalError('(pysqlite2.dbapi$
Traceback (most recent call last):
  File "/opt/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/server/mhn/tasks/__init__.py", line 13, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/opt/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/server/mhn/tasks/rules.py", line 82, in fetch_sources
    Rule.bulk_import(rules)
  File "/opt/server/mhn/api/models.py", line 185, in bulk_import
    rule.insert_refs(ru['references'])
  File "/opt/server/mhn/api/models.py", line 132, in insert_refs
    db.session.commit()
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
 File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) unable to open database file [SQL: u'INSERT INTO rules (message, classtype, sid, rev, date, rule_format, is_active, note$

**Comment by d1str0** [comment]
What operating system is this running on?

**Comment by jjjan** [comment]
ubuntu 16.04 server. i have the same issue on ubuntu 14 desktop before.

**Comment by jjjan** [comment]
update the server is solve this error. thx mhn keep going to upgrade
