### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/opt/cowrie/log/cowrie.log'

### ISSUE THREAD

**Issue by LowkeyFlex** [threatstream/mhn#497]
UPDATE:
When i try to start crowie with "cowrie start" i get the error permission denied
I used the deploy script of mhn on ubuntu server 16.04.3 LTS
It's a fresh VM with only mhn

```
max@ubuntu:/opt/cowrie$ bin/cowrie start
Activating virtualenv "cowrie-env"
Starting cowrie: [twistd -n  --umask 0077 --pidfile var/run/cowrie.pid -l log/cowrie.log cowrie ]...
Unhandled Error
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
--- <exception caught here> ---
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 170, in makeService
    globals(), locals(), ['output']).Output(cfg)
  File "/opt/cowrie/cowrie/output/jsonlog.py", line 52, in __init__
    self.outfile = twisted.python.logfile.DailyLogFile(base, dirs, defaultMode=0o664)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 248, in _openFile
    BaseLogFile._openFile(self)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 74, in _openFile
    self._file = open(self.path, "rb+", 0)
exceptions.IOError: [Errno 13] Permission denied: u'log/cowrie.json'

hpfeeds client init broker 192.168.71.156:10000, identifier f79b4eea-c548-11e7-a757-000c291012ef
hpclient established
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==17.9.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 382, in run
    self.logger.start(self.application)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 191, in start
    observer = self._getLogObserver()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 160, in _getLogObserver
    logFile = logfile.LogFile.fromFullPath(self._logfilename)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 54, in fromFullPath
    os.path.dirname(logPath), *args, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 74, in _openFile
    self._file = open(self.path, "rb+", 0)
IOError: [Errno 13] Permission denied: '/opt/cowrie/log/cowrie.log'

```

```
cowrie@ubuntu:/opt/cowrie/log$ stat cowrie.json
  File: 'cowrie.json'
  Size: 40781           Blocks: 88         IO Block: 4096   regular file
Device: 801h/2049d      Inode: 669215      Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/  cowrie)   Gid: (  100/   users)
Access: 2017-11-09 04:24:46.370176220 -0800
Modify: 2017-11-09 05:10:51.449945151 -0800
Change: 2017-11-09 05:10:51.449945151 -0800

```

```
max@ubuntu:/opt/cowrie/log$ stat cowrie.log
  File: 'cowrie.log'
  Size: 28112           Blocks: 64         IO Block: 4096   regular file
Device: 801h/2049d      Inode: 669217      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1001/  cowrie)   Gid: (  100/   users)
Access: 2017-11-09 04:24:46.926470618 -0800
Modify: 2017-11-09 05:10:51.449945151 -0800
Change: 2017-11-09 05:10:51.449945151 -0800
```

When chaning to user cowrie i get 
exceptions.IOError: [Errno 30] Read-only file system: u'log/cowrie.json'
IOError: [Errno 30] Read-only file system: '/opt/cowrie/log/cowrie.log'

**Comment by d1str0** [comment]
What operating system? Did you use the cowrie deploy script? How did you get to this point?

**Comment by LowkeyFlex** [comment]
I used mhn to install/deploy on ubuntu server 16.04.3 LTS
Update: Well i had something wrong in the config file, but now i get the following


> max@ubuntu:/opt/cowrie$ bin/cowrie start
Activating virtualenv "cowrie-env"
Starting cowrie: [twistd -n  --umask 0077 --pidfile var/run/cowrie.pid -l log/cowrie.log cowrie ]...
Unhandled Error
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
--- <exception caught here> ---
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 170, in makeService
    globals(), locals(), ['output']).Output(cfg)
  File "/opt/cowrie/cowrie/output/jsonlog.py", line 52, in __init__
    self.outfile = twisted.python.logfile.DailyLogFile(base, dirs, defaultMode=0o664)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 248, in _openFile
    BaseLogFile._openFile(self)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 74, in _openFile
    self._file = open(self.path, "rb+", 0)
exceptions.IOError: [Errno 13] Permission denied: u'log/cowrie.json'

hpfeeds client init broker 192.168.71.156:10000, identifier f79b4eea-c548-11e7-a757-000c291012ef
hpclient established
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==17.9.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 382, in run
    self.logger.start(self.application)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 191, in start
    observer = self._getLogObserver()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 160, in _getLogObserver
    logFile = logfile.LogFile.fromFullPath(self._logfilename)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 54, in fromFullPath
    os.path.dirname(logPath), *args, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 74, in _openFile
    self._file = open(self.path, "rb+", 0)
IOError: [Errno 13] Permission denied: '/opt/cowrie/log/cowrie.log'
max@ubuntu:/opt/cowrie$ sudo bin/cowrie start
Activating virtualenv "cowrie-env"
Starting cowrie: [twistd -n  --umask 0077 --pidfile var/run/cowrie.pid -l log/cowrie.log cowrie ]...
ERROR: You must not run cowrie as root!
max@ubuntu:/opt/cowrie$ sudo su
root@ubuntu:/opt/cowrie# bin/cowrie start
Activating virtualenv "cowrie-env"
Starting cowrie: [twistd -n  --umask 0077 --pidfile var/run/cowrie.pid -l log/cowrie.log cowrie ]...
ERROR: You must not run cowrie as root!
root@ubuntu:/opt/cowrie# ^C
root@ubuntu:/opt/cowrie# ^C
root@ubuntu:/opt/cowrie# exit
exit
max@ubuntu:/opt/cowrie$ bin/cowrie start
Activating virtualenv "cowrie-env"
Starting cowrie: [twistd -n  --umask 0077 --pidfile var/run/cowrie.pid -l log/cowrie.log cowrie ]...
Unhandled Error
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
--- <exception caught here> ---
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 170, in makeService
    globals(), locals(), ['output']).Output(cfg)
  File "/opt/cowrie/cowrie/output/jsonlog.py", line 52, in __init__
    self.outfile = twisted.python.logfile.DailyLogFile(base, dirs, defaultMode=0o664)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 248, in _openFile
    BaseLogFile._openFile(self)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 74, in _openFile
    self._file = open(self.path, "rb+", 0)
exceptions.IOError: [Errno 13] Permission denied: u'log/cowrie.json'

hpfeeds client init broker 192.168.71.156:10000, identifier f79b4eea-c548-11e7-a757-000c291012ef
hpclient established
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==17.9.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 382, in run
    self.logger.start(self.application)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 191, in start
    observer = self._getLogObserver()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 160, in _getLogObserver
    logFile = logfile.LogFile.fromFullPath(self._logfilename)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 54, in fromFullPath
    os.path.dirname(logPath), *args, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 74, in _openFile
    self._file = open(self.path, "rb+", 0)
IOError: [Errno 13] Permission denied: '/opt/cowrie/log/cowrie.log'
