### ISSUE TITLE
Mnemosyne error - Connection refused

### ISSUE THREAD

**Issue by miguextreme** [threatstream/mhn#519]
I was a bit confused why some of the suricata.events that where catched on suricata's sensor logs weren't appearing on my MHN interface. After some investigation on de MHN server side I discovered this error:
`==> /var/log/mhn/mnemosyne.err <==
2018-01-30 10:41:36,110 (pyhpfeeds) connecting to localhost:10000
Traceback (most recent call last):
  File "/opt/mnemosyne/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/socket.py", line 344, in connect
    raise error(err, strerror(err))
error: [Errno 111] Connection refused`

And yes, all the services are up and running when checking with `sudo supervisorctl status`...
Is there anyone who can help me?

Thanks in advance,
Miguel Rosa

**Comment by miguextreme** [comment]
After several hours searching this problem I've reached to something interesting as Gerda Mills observed:
[https://groups.google.com/forum/m/#!msg/modern-honey-network/ddcPxnSxTS8/i_As7EarCQAJ](url)
> Hi Jason,
>
>based on the latest observation I made some tests and came to the following conclusion:
>
>The problem always appears after the feedpuller reconnect error message because of 15 sec inactivity >(which is in my scenario very likely as I am running the sensor on the internal network). 
>
>If I increase the inactivity timeout all received events are stored inside database until the inactivity >timeout again is triggered.
>
>Looking into the code I am wondering why an inactivity timeout does NOT instantly lead to a forced >reconnect:
>
>mnemosyne/feedpuller/feedpuller.py:
>
> 72     def _activity_checker(self):
>    73         while self.enabled:
>     74             if self.hpc is not None and self.hpc.connected:
>     75                 difference = datetime.now() - self.last_received
>     76                 if difference.seconds > 300:
>     77                     logger.warning('No activity for Daniel 300 seconds, forcing reconnect')
>     78                     self.hpc.stop()
>     79             gevent.sleep(300)
>
>This reconnect is then only initiated if a new event arrives but that leads to the behaviour described >above. 
>
>As I guess that the inactivity timeout itself make sense I don't want to increase the timer which solve >the problem itself not really.
>
>I hope my observations are correct and you could guide me in fixing this behaviour.
>
>thanks

As I am using MHN project in the internal network I have very few alerts and with that error when I get the alerts I am always losing the first alert because it is reconnecting... My solution? Just commented these 78th line where it says `self.hpc.stop()` so that it never goes to the inactivity state. After restarting mnemosyne I started receiving all the alerts as it was supposed.

Is there a better solution? Am I doing something very prejudicial to the MHN?
