### ISSUE TITLE
Installation issues with Supervisor and Python

### ISSUE THREAD

**Issue by maxw7** [threatstream/mhn#538]
Hi,
I'm having some problems installing MHN on CentOS7. 
After rebooting I get the following error when calling supervisorctl:
 
[root@CP71SRVSEC171T2 ldx1werner]# supervisorctl
unix:///tmp/supervisor.sock no such file

If I then uninstall/install supervisor again using pip, this issue is gone. How is it possible that supervisor  fails after a reboot (every time!) and needs to be reinstalled?

The other error I've been trying to fix for two days is in the installation script install_mhnserver.sh.
Running this script gives the following error:

+ /usr/local/bin/virtualenv -p /usr/local/bin/python2.7 env
Already using interpreter /usr/local/bin/python2.7
New python executable in /opt/mhn/env/bin/python2.7
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1231, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/local/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/opt/mhn/env/bin/python2.7'

In my understanding, this is caused by two python processes simultaneously trying to access the same python file. I've since then been experimenting with virtualenv and the python installation but couldn't come up with any fix. Any help would be appreciated!

Typing ps -ef | grep python shows the following processes:

[root@CP71SRVSEC171T1 scripts]# ps -ef | grep python
root       853     1  0 10:44 ?        00:00:00 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid
root      1163     1  0 10:44 ?        00:00:01 /usr/bin/python -Es /usr/sbin/tuned -l -P
root      2179     1  0 11:00 ?        00:00:05 /usr/local/bin/python2.7 /usr/local/bin/supervisord -c /etc/supervisord.conf
root      2182  2179  0 11:00 ?        00:00:00 /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/feedbroker.py
root      2183  2179  0 11:00 ?        00:00:03 /opt/mnemosyne/env/bin/python runner.py --config mnemosyne.cfg
root      2184  2179  0 11:00 ?        00:00:00 /opt/hpfeeds/env/bin/python /opt/hpfeeds/examples/geoloc/geoloc.py /opt/hpfeeds/geoloc.json
root      2187  2179  0 11:00 ?        00:00:00 /opt/mhn/env/bin/python collector_v2.py collector.json
nginx     7747  2179  0 12:38 ?        00:00:00 /opt/mhn/env/bin/python2.7 /opt/mhn/env/bin/celery worker -A mhn.tasks --loglevel=INFO
nginx     7752  7747  0 12:38 ?        00:00:00 /opt/mhn/env/bin/python2.7 /opt/mhn/env/bin/celery worker -A mhn.tasks --loglevel=INFO
nginx     7753  7747  0 12:38 ?        00:00:00 /opt/mhn/env/bin/python2.7 /opt/mhn/env/bin/celery worker -A mhn.tasks --loglevel=INFO
root     10224  2179  0 14:43 ?        00:00:00 /opt/mhn/env/bin/python2.7 /opt/mhn/env/bin/celery beat -A mhn.tasks --loglevel=INFO
root     10339  9857  0 14:44 pts/1    00:00:00 grep --color=auto python

**Comment by d1str0** [comment]
Last I tested Centos 7 was on DigitalOcean. Are you using a cloud host? If so, which one?

Will test again. Thanks.

**Comment by maxw7** [comment]
I'm not using a cloud host, I'm using the official DVD iso I downloaded from centos.org. Thanks!

**Comment by hackunagi** [comment]
I'm using a Centos 7 on Digital Ocean and having similar issues. Below the logs generated.

+ mkdir -p /var/log/mhn
+ mkdir -p /etc/supervisor/
+ mkdir -p /etc/supervisor/conf.d
+ cat
+ ldconfig /usr/local/lib/
+ /etc/init.d/supervisor start
./install_hpfeeds.sh: line 92: /etc/init.d/supervisor: No such file or directory
+ true
+ sleep 5
+ supervisorctl update
error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/local/lib/python2.7/socket.py line: 224

**Comment by kkkkkky** [comment]
Is there anyone following this bug ? I have similar issue during deployment in CentOS 7.

**Comment by kkkkkky** [comment]
`rm -rf /opt/mhn/env ` solved this issue.

**Comment by kkkkkky** [comment]
> I'm using a Centos 7 on Digital Ocean and having similar issues. Below the logs generated.
> ...
> 
> * mkdir -p /var/log/mhn
> * mkdir -p /etc/supervisor/
> * mkdir -p /etc/supervisor/conf.d
> * cat
> * ldconfig /usr/local/lib/
> * /etc/init.d/supervisor start
>   ./install_hpfeeds.sh: line 92: /etc/init.d/supervisor: No such file or directory
> * true
> * sleep 5
> * supervisorctl update
>   error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/local/lib/python2.7/socket.py line: 224

This is because supervisord service not started. You could try to run `supervisord -c /etc/supervisord.conf` before running install.sh. This method worked for me.
