### ISSUE TITLE
Traceback - generateconfig.py --> install_mhnserver.sh --> error

### ISSUE THREAD

**Issue by packet808** [threatstream/mhn#544]
Traceback (most recent call last):
  File "generateconfig.py", line 179, in <module>
    generate_config()
  File "generateconfig.py", line 27, in generate_config
    pub_ip = json.load(urlopen('http://httpbin.org/ip'))['origin']
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by d1str0** [comment]
This needs more information. What OS? What hardware? When did this occur?

**Comment by elals** [comment]
Hello i have similar ISSUE when try install MHN on a UBUNTU 18, 
Its any vary help me plase, all ready try upgrade UBUNTU, reinstall PIP and update

ERROR MESSAGE:
python generateconfig.py
Traceback (most recent call last):
  File "generateconfig.py", line 184, in <module>
    generate_config()
  File "generateconfig.py", line 32, in generate_config
    pub_ip = get_pub_ip()
  File "generateconfig.py", line 21, in get_pub_ip
    sock = urlopen('http://icanhazip.com/')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
