### ISSUE TITLE
Cowrie feeds

### ISSUE THREAD

**Issue by dariogomez** [threatstream/mhn#552]
When you finish the cowrie install, the sensor didn't report the events to the server.

I look at the cowrie log and throws this error:
    if CONFIG.getboolean(x, 'enabled') is False:
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'enabled' in section: u'output_hpfeeds'

The cowrie.cfg file, on "output_hpfeeds" settings, has a new variable called enabled that you have to set on true. When you made it, the sensor start sending the feed to the MHN server.

This is an example of the cowrie config file on the cowrie github repo:

#[output_hpfeeds]
#enabled = false
#server = hpfeeds.mysite.org
#port = 10000
#identifier = abc123
#secret = secret
#debug=false

**Comment by 4n6strider** [comment]
I have the same issue.  Cowrie installation from MHN is not working anymore. Sensor gets installed and regiesterd with MHN server, but it crashes and cant be started at all.

Output of the error log:

Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    sys.exit(run())
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 159, in makeService
    if CONFIG.getboolean(x, 'enabled') is False:
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'enabled' in section: u'output_hpfeeds'

**Comment by ahmedkhiar** [comment]
all you have to do is to uncomment the ligne :
#enabled = false and set it to true.
Hope it helps !

**Comment by dariogomez** [comment]
@ahmedkhiar I made the same and works! I've reported to the authors to fix it on future versions.

**Comment by 4n6strider** [comment]
@ahmedkhiar Thank you a lot! That was the solution which worked for me.
