### ISSUE TITLE
MHN Glastopf script Breaking while installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by MarcoGeek** [threatstream/mhn#554]
I am experiencing issue while installing glastopf though MHN server on Ubuntu 14.04. Could you please suggest any options. Below is the error message:

Installed /usr/local/lib/python2.7/dist-packages/WebOb-1.8.1-py2.7.egg
Searching for python-dateutil>=2.1,<3.0.0
Reading https://pypi.python.org/simple/python-dateutil/
Best match: python-dateutil 2.7.3
Downloading https://files.pythonhosted.org/packages/a0/b0/a4e3241d2dee665fea11baec21389aec6886655cd4db7647ddf96c3fad15/python-dateutil-2.7.3.tar.gz#sha256=e27001de32f627c22380a688bcc43ce83504a7bc5da472209b4c70f02829f0b8
Processing python-dateutil-2.7.3.tar.gz
Writing /tmp/easy_install-HgVcmo/python-dateutil-2.7.3/setup.cfg
Running python-dateutil-2.7.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HgVcmo/python-dateutil-2.7.3/egg-dist-tmp-9Cc7v7
/tmp/easy_install-HgVcmo/python-dateutil-2.7.3/setup.py:19: UserWarning: python_requires requires setuptools version > 24.3
  UserWarning)
Searching for setuptools-scm
Reading https://pypi.python.org/simple/setuptools_scm/
Best match: setuptools-scm 2.1.0
Downloading https://files.pythonhosted.org/packages/11/d7/8a5d8aa5df10a48f388c87c8b96288f6db53c92fe23a367fbe9d4bd725a8/setuptools_scm-2.1.0-py2.7.egg#sha256=0f386524bb99d959e0d98381d7fe1f0a810e04eace5d2cc6297e701d64de9a7d
Processing setuptools_scm-2.1.0-py2.7.egg
Moving setuptools_scm-2.1.0-py2.7.egg to /tmp/easy_install-HgVcmo/python-dateutil-2.7.3

Installed /tmp/easy_install-HgVcmo/python-dateutil-2.7.3/setuptools_scm-2.1.0-py2.7.egg
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    install_requires=open('requirements.txt').read().splitlines(),
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 86, in <module>

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/easy_install-HgVcmo/python-dateutil-2.7.3/setuptools_scm-2.1.0-py2.7.egg/setuptools_scm/integration.py", line 10, in version_keyword
  File "/tmp/easy_install-HgVcmo/python-dateutil-2.7.3/setuptools_scm-2.1.0-py2.7.egg/setuptools_scm/version.py", line 44, in _warn_if_setuptools_outdated
setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

Thanks in advance.

**Comment by freegit9527** [comment]
before install Glastopf, you can install easy_install and pip whit the new version by yourself .

**Comment by freegit9527** [comment]
and I met a error ,when I start Glastopf ,


Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 4, in <module>
    __import__('pkg_resources').run_script('Glastopf==3.1.3.dev0', 'glastopf-runner')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 654, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1434, in run_script
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 91, in <module>
    honeypot = GlastopfHoneypot(work_dir=args.workdir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/glastopf.py", line 65, in __init__
    self.loggers = logging_handler.get_aux_loggers(self.data_dir, self.work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/logging_handler.py", line 49, in get_aux_loggers
    logger_instance = logger_class(data_dir, work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/reporting/auxiliary/log_s3.py", line 35, in __init__
    self.enabled = self.config.getboolean("s3storage", "enabled")
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 's3storage'

**Comment by freegit9527** [comment]
my problem solved
add this in glastopf.cfg 
[s3storage]
enabled = False
endpoint = http://localhost:8080/
aws_access_key_id = YOUR_aws_access_key_id
aws_secret_access_key = YOUR_aws_access_key_id
bucket = glastopf
region = eu-west-1
signature_version = s3

**Comment by MarcoGeek** [comment]
Thanks...Let me try that.

**Comment by MarcoGeek** [comment]
Glastopf got some serious problem with MHN script. I tried multiple times and tried upgrading the packge nothing helped me.

config.status: executing libtool commands
+ make
/bin/bash /opt/BFR/libtool --mode=compile cc -Werror -Wall -I. -I/opt/BFR -DPHP_ATOM_INC -I/opt/BFR/include -I/opt/BFR/main -I/opt/BFR -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/BFR/php_bfr.c -o php_bfr.lo
libtool: compile:  cc -Werror -Wall -I. -I/opt/BFR -DPHP_ATOM_INC -I/opt/BFR/include -I/opt/BFR/main -I/opt/BFR -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/BFR/php_bfr.c  -fPIC -DPIC -o .libs/php_bfr.o
/opt/BFR/php_bfr.c: In function 'zif_override_function':
/opt/BFR/php_bfr.c:152:2: error: implicit declaration of function 'zend_hash_str_find_ptr' [-Werror=implicit-function-declaration]
  if ((func = zend_hash_str_find_ptr(EG(function_table),
  ^
/opt/BFR/php_bfr.c:152:12: error: assignment makes pointer from integer without a cast [-Werror]
  if ((func = zend_hash_str_find_ptr(EG(function_table),
            ^
/opt/BFR/php_bfr.c:163:2: error: implicit declaration of function 'zend_hash_str_exists' [-Werror=implicit-function-declaration]
  if (zend_hash_str_exists(EG(function_table),
  ^
/opt/BFR/php_bfr.c:166:3: error: implicit declaration of function 'zend_hash_str_del' [-Werror=implicit-function-declaration]
   zend_hash_str_del(EG(function_table),
   ^
/opt/BFR/php_bfr.c:170:2: error: implicit declaration of function 'zend_hash_str_add_new_ptr' [-Werror=implicit-function-declaration]
  if (zend_hash_str_add_new_ptr(EG(function_table),
  ^
/opt/BFR/php_bfr.c:172:19: error: comparison between pointer and integer [-Werror]
         func_dup) == NULL)
                   ^
/opt/BFR/php_bfr.c: In function 'zif_rename_function':
/opt/BFR/php_bfr.c:207:12: error: assignment makes pointer from integer without a cast [-Werror]
  if ((func = zend_hash_str_find_ptr(EG(function_table),
            ^
/opt/BFR/php_bfr.c:227:2: error: implicit declaration of function 'zend_hash_str_add_ptr' [-Werror=implicit-function-declaration]
  if (zend_hash_str_add_ptr(EG(function_table), z_new_fname, new_fname_len, func_dup) == NULL)
  ^
/opt/BFR/php_bfr.c:227:86: error: comparison between pointer and integer [-Werror]
  if (zend_hash_str_add_ptr(EG(function_table), z_new_fname, new_fname_len, func_dup) == NULL)
                                                                                      ^
cc1: all warnings being treated as errors
make: *** [php_bfr.lo] Error 1
++ lsb_release -r -s
+ '[' 14.04 == 14.04 ']'
++ find /usr/lib/php5/ -type f -name bfr.so
++ awk -F/ '{print $5}'
+ BFR_BUILD_OUTPUT=
+ echo 'zend_extension = /usr/lib/php5//bfr.so'
+ service apache2 stop
 * Stopping web server apache2                                                                                                                                           *
+ update-rc.d -f apache2 remove
 Removing any system startup links for /etc/init.d/apache2 ...
+ pip install --upgrade greenlet
The directory '/home/impact/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/impact/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Requirement already up-to-date: greenlet in /usr/local/lib/python2.7/dist-packages (0.4.13)
cheetah 2.4.4 requires Markdown>=2.0.1, which is not installed.
libtaxii 1.1.110 requires python-dateutil>=1.4.1, which is not installed.
botocore 1.10.58 requires docutils>=0.10, which is not installed.
botocore 1.10.58 requires jmespath<1.0.0,>=0.7.1, which is not installed.
botocore 1.10.58 requires python-dateutil<3.0.0,>=2.1, which is not installed.
jinja2 2.10 requires MarkupSafe>=0.23, which is not installed.
libtaxii 1.1.110 has requirement six>=1.9.0, but you'll have six 1.5.2 which is incompatible.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
+ pip install --upgrade pgen
The directory '/home/impact/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/impact/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Requirement already up-to-date: pgen in /usr/local/lib/python2.7/dist-packages (0.2.1)
cheetah 2.4.4 requires Markdown>=2.0.1, which is not installed.
libtaxii 1.1.110 requires python-dateutil>=1.4.1, which is not installed.
botocore 1.10.58 requires docutils>=0.10, which is not installed.
botocore 1.10.58 requires jmespath<1.0.0,>=0.7.1, which is not installed.
botocore 1.10.58 requires python-dateutil<3.0.0,>=2.1, which is not installed.
jinja2 2.10 requires MarkupSafe>=0.23, which is not installed.
libtaxii 1.1.110 has requirement six>=1.9.0, but you'll have six 1.5.2 which is incompatible.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
+ pip install --upgrade cython
The directory '/home/impact/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/impact/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Requirement already up-to-date: cython in /usr/local/lib/python2.7/dist-packages (0.28.4)
cheetah 2.4.4 requires Markdown>=2.0.1, which is not installed.
libtaxii 1.1.110 requires python-dateutil>=1.4.1, which is not installed.
botocore 1.10.58 requires docutils>=0.10, which is not installed.
botocore 1.10.58 requires jmespath<1.0.0,>=0.7.1, which is not installed.
botocore 1.10.58 requires python-dateutil<3.0.0,>=2.1, which is not installed.
jinja2 2.10 requires MarkupSafe>=0.23, which is not installed.
libtaxii 1.1.110 has requirement six>=1.9.0, but you'll have six 1.5.2 which is incompatible.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
+ pip uninstall --yes setuptools
The directory '/home/impact/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling setuptools-33.1.1:
  Successfully uninstalled setuptools-33.1.1
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 246, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/basecommand.py", line 264, in main
    timeout=min(5, options.timeout)) as session:
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 338, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 127, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/misc.py", line 829, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 558, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 614, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1882, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1399, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1756, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1633, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1590, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/setuptools-33.1.1-py2.7.egg'

**Comment by mobsonline** [comment]
Gentlemen, I have had the same experience. Just wondering if you were able to dig down into the root cause of the issue. I shall greatly appreciate any information as I would very much love to limit the manual configurations on the deployment.

I was able to make it run by following some of the tips I found, including the [s3storage] workaround by FREEGIT9527 by altering the glastop.cfg and additionally to force the Glastopf-runner to use pywsgi instead of wsgi (line 10 of the glastop-runner). This essentially brought the honeypot to life. But unable to see at what point does it actually break.

**Comment by AgoraSecurity** [comment]
> my problem solved
> add this in glastopf.cfg
> [s3storage]
> enabled = False
> endpoint = http://localhost:8080/
> aws_access_key_id = YOUR_aws_access_key_id
> aws_secret_access_key = YOUR_aws_access_key_id
> bucket = glastopf
> region = eu-west-1
> signature_version = s3

This also solved my issue! :)
