### ISSUE TITLE
Cowrie Not feeding in the data to MHN

### ISSUE THREAD

**Issue by secstu** [threatstream/mhn#564]
Hey!
So after playing around with MHN i have to give it up! Its a very very solid project and kudos to the developpers and people who are commiting!
After installing cowrie on a Ubutnu 14 64x system i got it to run using the latest commit #555!
But i have found myself in a situation that i cant understand.
It seems that cowrie is running but its not connecting to hpfeeds Following error appears:
`
2018-06-06T22:40:44.599613+0000 [-] Twisted Version 18.4.0
2018-06-06T22:40:44.601075+0000 [-] Loaded output engine: jsonlog
2018-06-06T22:40:44.601729+0000 [-] Early version of hpfeeds-output, untested!
2018-06-06T22:40:44.601979+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
            runApp(config)
          File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
            runner.run()
          File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
            self.application = self.createOrGetApplication()
          File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
            ser = plg.makeService(self.config.subOptions)
        --- <exception caught here> ---
          File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 164, in makeService
            globals(), locals(), ['output']).Output()
          File "/opt/cowrie/cowrie/output/hpfeeds.py", line 270, in __init__
            cowrie.core.output.Output.__init__(self)
          File "/opt/cowrie/cowrie/core/output.py", line 107, in __init__
            self.start()
          File "/opt/cowrie/cowrie/output/hpfeeds.py", line 279, in start
            secret = CONFIG.get('output_hpfeeds', 'secret')
          File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
            raise NoOptionError(option, section)
        backports.configparser.NoOptionError: No option 'secret' in section: 'output_hpfeeds'
`
So i tried messing around and edited my cowrie to un-comment #secret = secret
And then i got the error about No option 'debug' in section: 'output_hpfeeds'
So i un-commented again the # beside debug=false and when i try to restart cowrie i get the following error:
$sudo -H -u cowrie bash -c "./cowrie start"
Using default Python virtual environment "/opt/cowrie/cowrie-env"
Starting cowrie: [twistd -n  --umask 0022 --pidfile var/run/cowrie.pid --logger cowrie.python.logfile.logger cowrie ]...
'errormessage from server: 617574686661696c2e'
I can see cowrie running perfectly if i go into the log. But its not feeding correctly into the mhn. I tried even enabling cross vps communication by enabling port 10000 on the mhn vps firewall - still nothing.
Anyone fancy giving this a go?
Thanks for the time and again for this awesome project!

**Comment by secstu** [comment]
I have been trying to solve this further. I tried entering the secret for the mnemosyne which seems to have cowrie.sessions and kippo.sessions attached to it. I tried entering in the format : 'secret = 555174f44a7.......hash....." ' and 'secret = hash' (no brackets).

I was thinking to change it but i'm not sure if that wont break any other stuff since I'm a total noob in mongodb.

I'm getting frustrated at this stage but i really cant wait to get this fully running.
Also the map doesn't load it for me ? Even on a fresh install.

**Comment by d1str0** [comment]
Did you use the packaged cowrie installation script to install Cowrie?

**Comment by d1str0** [comment]
Try again with the latest cowrie install script.
