### ISSUE TITLE
hpfeed.py timeout: timed out

### ISSUE THREAD

**Issue by dipenpatel235** [threatstream/mhn#590]
==> /var/log/mhn/mhn-collector.err <==
Traceback (most recent call last):
  File "/opt/mnemosyne/src/hpfeeds/lib/hpfeeds.py", line 138, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

**Comment by d1str0** [comment]
What's the output of `sudo supervisorctl status`?

**Comment by dpicollege** [comment]
and also hpfeeds logger has this issue

Traceback (most recent call last):
  File "/opt/hpfeeds-logger/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

**Comment by dpicollege** [comment]
with supervisor. does it need any permission for mongo or any things else. Connection refused by mongo or whatever?

**Comment by dipenpatel235** [comment]
```
supervisorctl status
geoloc                           RUNNING   pid 1298, uptime 4:54:07
honeymap                         RUNNING   pid 1307, uptime 4:54:06
hpfeeds-broker                   RUNNING   pid 1296, uptime 4:54:07
mhn-celery-beat                  RUNNING   pid 1292, uptime 4:54:08
mhn-celery-worker                RUNNING   pid 1301, uptime 4:54:06
mhn-collector                    RUNNING   pid 1303, uptime 4:54:06
mhn-uwsgi                        RUNNING   pid 1300, uptime 4:54:07
mnemosyne                        RUNNING   pid 1297, uptime 4:54:07
```

**Comment by d1str0** [comment]
Are you still having this issue?

**Comment by jtsamas** [comment]
hi @d1str0 

I am getting the same
sudo tail /var/log/mhn/mhn-collector.err
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out
Traceback (most recent call last):
  File "/home/nawa/mhn/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out


and maybe related to my issue... https://github.com/threatstream/mhn/issues/704.

Please help

**Comment by 4n6strider** [comment]
I have the issue as well. Maybe some dependencies compatibility changed after "update" ?
