### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by gusman222** [threatstream/mhn#599]
Hi there!!

I've recently installed MHN on a Ubuntu 18.04 VM (virtualbox). The thing is, when i try to access the web interface, i can perform the login but instead of the start page i get an: 

"500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

What can i do to solve this problem?

Ths
mhn.log:
2018-10-11 17:10:07,910 -  /opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py - Exception on / [GET]
Traceback (most recent call last):
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "./mhn/ui/views.py", line 62, in dashboard
    top_attackers = clio.session.top_attackers(top=5, hours_ago=24)
  File "./mhn/common/clio.py", line 316, in top_attackers
    return self._tops('source_ip', top, hours_ago)
  File "./mhn/common/clio.py", line 304, in _tops
    res = self.collection.aggregate(query)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 1336, in aggregate
    "aggregate", self.__name, **command_kwargs)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/database.py", line 351, in _command
    msg, allowable_errors)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/helpers.py", line 178, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('aggregate', u'session'), ('pipeline', [{'$match': {'timestamp': {'$gte': datetime.datetime(2018, 10, 10, 17, 10, 7, 910057)}, 'source_ip': {'$ne': None}}}, {'$group': {'count': {'$sum': 1}, '_id': {'source_ip': '$source_ip'}}}, {'$sort': SON([('count', -1)])}])]) failed: The 'cursor' option is required, except for aggregate with the explain argument

**Comment by d1str0** [comment]
The mongo interface is broken. I still need to fix it. :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d1str0** [comment]
Please try with the code from PR #602 

```cd /opt/mhn && sudo git checkout mongodb && sudo supervisorctl restart all```

**Comment by d1str0** [comment]
Fixed by #602
