### ISSUE TITLE
Glastopf - auto run issue

### ISSUE THREAD

**Issue by xxmoC** [threatstream/mhn#614]
Hi,

I am trying to get Glastopf-runner auto started. When I manually start it it's running without any issues and my events are even pushed to MHN. 

However when trying to get it in supervisorctl it's giving fatal errors: 

```
root@HP-Glastopf:/opt/glastopf/bin/log# supervisorctl status all
glastopf                         FATAL     Exited too quickly (process log may have details)
```

Config:

```
[program:glastopf]
command=/usr/bin/python /opt/glastopf/bin/glastopf-runner
directory=/opt/glastopf
stdout_logfile=/var/log/glastopf.out
stderr_logfile=/var/log/glastopf.err
autostart=true
autorestart=true
redirect_stderr=true
stopsignal=QUIT
```

Should be ok I guess?

**Comment by d1str0** [comment]
Very strange. And manually, you are running exactly, "/usr/bin/python /opt/glastopf/bin/glastopf-runner"?

**Comment by AgoraSecurity** [comment]
I'm also having issues:
```
root@ubuntu-Glastopf:/opt/glastopf# sudo supervisorctl status
glastopf                         FATAL     Exited too quickly (process log may have details)
root@ubuntu-Glastopf:/opt/glastopf# /usr/bin/python /usr/local/bin/glastopf-runner
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 4, in <module>
    __import__('pkg_resources').run_script('Glastopf==3.1.3.dev0', 'glastopf-runner')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 131, in <module>
    honeypot = GlastopfHoneypot(work_dir=args.workdir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/glastopf.py", line 65, in __init__
    self.loggers = logging_handler.get_aux_loggers(self.data_dir, self.work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/logging_handler.py", line 49, in get_aux_loggers
    logger_instance = logger_class(data_dir, work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/reporting/auxiliary/log_s3.py", line 35, in __init__
    self.enabled = self.config.getboolean("s3storage", "enabled")
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 's3storage'
root@ubuntu-Glastopf:/opt/glastopf# 
```

OS:
```
root@ubuntu-Glastopf:/opt/glastopf# uname -a
Linux ubuntu-Glastopf 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu-Glastopf:/opt/glastopf# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by f1r3walled** [comment]
@xxmoC, are you using Ubuntu 18, too?

**Comment by d1str0** [comment]
@AgoraSecurity @xxmoC if you use the latest install script you should no longer have this issue. 

Please update us on if this works or not.

**Comment by xxmoC** [comment]
@d1str0 thanks, I'll give it a shot 👍
