### ISSUE TITLE
Real time map issues 

### ISSUE THREAD

**Issue by Mrflao** [threatstream/mhn#623]
Hi  guys. 

I have a problem with real time map . It shows  wrong attack sources , I mean  in <Attacks> section all are correct but in real time map it shows or wrong country (attack can be from China but map shows USA ) or nothing  ( especially  EU zone ). 

Sometime it shows correct only from specific regions ^^

Because  we have little issues with Geoloc files I downloaded   old versions 

wget http://45.62.212.159/packages/GeoLiteCity.dat.gz && gzip -d GeoLiteCity.dat.gz
wget http://45.62.212.159/packages/GeoLiteCityv6.dat.gz && gzip -d GeoLiteCityv6.dat.gz
wget http://45.62.212.159/packages/GeoIPASNum.dat.gz && gzip -d GeoIPASNum.dat.gz

All in status RUNNING 

geolog.log is empyt 

geoloc.err  

Traceback (most recent call last):
File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
self.s.connect((addr, self.port))
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Parsing config file: /opt/hpfeeds/geoloc.json
Traceback (most recent call last):
File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
self.s.connect((addr, self.port))
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Traceback (most recent call last):
File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
self.s.connect((addr, self.port))
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Traceback (most recent call last):
File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
self.s.connect((addr, self.port))
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
connected to @hp2
 
Thank u!

**Comment by d1str0** [comment]
Should be fixed with latest code.

**Comment by Mrflao** [comment]
oh nice . Thank you !
