### ISSUE TITLE
ERROR:root:code for hash md5 was not found.

### ISSUE THREAD

**Issue by noahclements** [threatstream/mhn#624]
After doing "sudo ./install.sh", the script gets up to cloning hpfeeds and breaks.

```
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 ev.h ev++.h event.h '/usr/local/include'
 /bin/mkdir -p '/usr/local/share/man/man3'
 /usr/bin/install -c -m 644 ev.3 '/usr/local/share/man/man3'
make[1]: Leaving directory '/tmp/libev-4.15'
+ ldconfig /usr/local/lib/
+ mkdir -p /opt
+ cd /opt
+ rm -rf /opt/hpfeeds
+ git clone https://github.com/threatstream/hpfeeds
Cloning into 'hpfeeds'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 915 (delta 0), reused 0 (delta 0), pack-reused 908
Receiving objects: 100% (915/915), 790.01 KiB | 1.40 MiB/s, done.
Resolving deltas: 100% (418/418), done.
+ chmod 755 -R hpfeeds
+ cd hpfeeds
+ /usr/local/bin/virtualenv -p /usr/local/bin/python env
Running virtualenv with interpreter /usr/local/bin/python
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
New python executable in /opt/hpfeeds/env/bin/python
Command /opt/hpfeeds/env/bin/python -m pip config list had error code 255
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2567, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1088, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 964, in _install_wheel_with_search_dir
    config = _pip_config(py_executable, python_path)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1043, in _pip_config
    config[key] = ast.literal_eval(value)
  File "/usr/local/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    __get_hash(__func_name)
    ^
IndentationError: unexpected indent

```

**Comment by noahclements** [comment]
this was done on Ubuntu 18.04, i did a fresh install of Ubuntu 16.04 instead and this problem doesn't arise anymore. 

The problem comes from `/usr/local/bin/virtualenv -p /usr/local/bin/python env`, as I was able to enter that into my terminal and get the same error.

**Comment by d1str0** [comment]
I don't currently have any issues installing on 18.04 on Digital Ocean. Are you using a cloud host or your own hardware?

**Comment by noahclements** [comment]
my own hardware

**Comment by d1str0** [comment]
Since you are the only one with this issue at the moment and it is working for you under 16.04, I will be closing this issue.

If others experience this I will gladly reopen.
