### ISSUE TITLE
No attack data in the dashboard

### ISSUE THREAD

**Issue by JoSas1** [threatstream/mhn#653]
I've a fresh installation of MHN dashboard.
when I deploy a honeypot (suricata) the installation is fine.
my problem is when I start a NMAP scan to the honeypot the dashboard shows no data.

The suricata honeypot and MHN dashboard server are on the same network

I've tried to restart the service with:
sudo supervisorctl restart all

output:
mhn-collector: stopped
honeymap: stopped
geoloc: stopped
mhn-celery-beat: stopped
mnemosyne: stopped
mhn-uwsgi: stopped
hpfeeds-broker: stopped
mhn-celery-worker: ERROR (spawn error)
mhn-celery-beat: started
honeymap: started
mnemosyne: started
geoloc: started
mhn-uwsgi: started
mhn-collector: started
hpfeeds-broker: started

I've looked in the logfile from mhn-celery-worker:
Traceback (most recent call last):
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/worker/consumer/connection.py", line 23, in start
    c.connection = c.connect()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 405, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 412, in connection_for_read
    self.app.connection_for_read(heartbeat=heartbeat))
  File "/opt/mhn/env/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 436, in ensure_connected
    callback=maybe_shutdown,
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 496, in __init__
    self.Client = self._get_client()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 957, in _get_client
    'You have {0.__version__}'.format(redis))
VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.3

I've tried to upgrade the redis-py client but i dont know of I do this fine
sudo clone https://github.com/antirez/redis.git
sudo python setup.py install

This also not fix my problem.

What can I do to fix my problem?

**Comment by f1r3walled** [comment]
I had the same problem.
I solved with a new and fresh installation, but after `git clone https://www.github.com/threatstream/mhn.git` and before execute `./install`, I changed the file /opt/mhn/server/requirements.txt, indicating redis==3.2.1 instead using the default redis==2.10.3.
Just edit requirements.txt and execute it with `pip install -r requirements.txt` in a broken installation did not work for me. Again, a fresh installation was required.
Hope it helps!

**Comment by JoSas1** [comment]
f1r3walled thanks for your solution!
It solves the problem!

**Comment by hariomenkel** [comment]
If someone else stumbles across this problem: Reinstalling isn't neccessary. In my case the following was sufficient:

```
cd /opt/mhn/env/bin
sudo ./pip install --upgrade redis
```


Afterwards try

`sudo supervisorctl start mhn-celery-worker`

**Comment by d1str0** [comment]
This should be fixed in master now.
