### ISSUE TITLE
Restoring MHN from backup doesn't work

### ISSUE THREAD

**Issue by coonsmatthew** [threatstream/mhn#658]
I'm trying to backup and restore my MHN server, and am following the instructions here: https://github.com/threatstream/mhn/wiki/Backing-Up-and-Restoring-MHN#restore. 

Everything goes well, until I try to start the services, and I see this set of errors, which makes me think that the passwords are not successfully imported: 

```
INFO:root:Database ready.
INFO:root:Auth failure by mnemosyne.
INFO:root:Auth failure by mnemosyne.
INFO:root:Auth failure by honeymap.
INFO:root:Auth failure by mnemosyne.
INFO:root:Auth failure by mnemosyne.
INFO:root:Auth success by collector.
INFO:root:Auth failure by geoloc.
Traceback (most recent call last):
  File "/opt/hpfeeds/env/src/evnet-dev/evnet/__init__.py", line 569, in _readable
    self._event('read', data)
  File "/opt/hpfeeds/env/src/evnet-dev/evnet/util.py", line 16, in _event
    cb(*args)
  File "/opt/hpfeeds/env/src/evnet-dev/evnet/mongodb.py", line 118, in read
    p._resolve(buf)
  File "/opt/hpfeeds/env/src/evnet-dev/evnet/promise.py", line 73, in _resolve
    self._call_callbacks()
  File "/opt/hpfeeds/env/src/evnet-dev/evnet/promise.py", line 33, in _call_callbacks
    fn(self._result, *args, **kwargs)
  File "/opt/hpfeeds/broker/feedbroker.py", line 117, in checkauth
    self.io_in(b'')
  File "/opt/hpfeeds/broker/feedbroker.py", line 154, in io_in
    self.error('identfail.')
  File "/opt/hpfeeds/broker/feedbroker.py", line 193, in error
    self.conn.write(self.msgerror(emsg))
  File "/opt/hpfeeds/env/src/evnet-dev/evnet/__init__.py", line 505, in write
    raise EVException('Already closed.')
EVException: Already closed.
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 290, in <module>
    sys.exit(main())
  File "/opt/hpfeeds/broker/feedbroker.py", line 286, in main
    loop()
  File "/opt/hpfeeds/env/src/evnet-dev/evnet/__init__.py", line 47, in loop
    l.start()
pyev.Error: unspecified libev error: <pyev.Io object at 0x7fd2db74a680> has been stopped
```

When I run the second database restore (the restore that adds the authentication keys I do believe), here's the output. It almost makes it seem like it's not restoring the database auth keys, just the client auth keys, but I'm not really sure what I'm looking at: 

```
root@server:/var/lib/mongodb/backup/dump/hpfeeds# for FILE in *.bson;
> do 
>     mongorestore --drop --db hpfeeds "$FILE"
> done
2019-05-06T12:48:22.148-0400	checking for collection data in auth_key.bson
2019-05-06T12:48:22.151-0400	reading metadata for hpfeeds.auth_key from auth_key.metadata.json
2019-05-06T12:48:22.162-0400	restoring hpfeeds.auth_key from auth_key.bson
2019-05-06T12:48:22.223-0400	no indexes to restore
2019-05-06T12:48:22.223-0400	finished restoring hpfeeds.auth_key (108 documents)
2019-05-06T12:48:22.223-0400	done
2019-05-06T12:48:22.235-0400	checking for collection data in system.indexes.bson
2019-05-06T12:48:22.236-0400	done

```

**Comment by d1str0** [comment]
Unfortunately, MHN uses both a SQLite database (a flat file) and also Mongodb. Mongodb stores hpfeeds related things (like connection credentials, etc) and attack data. The SQLite db stores web app and sensor details (like the existence of sensors).

**Comment by coonsmatthew** [comment]
Thanks @d1str0, So I should restore the SQLite database as well I'm assuming? Do you know the location of that file so I can move it to our new system. What I'm trying to do is upgrade from Ubuntu 14 to 16 and not lose all of our sensors that we've deployed.

**Comment by coonsmatthew** [comment]
@d1str0 After looking at the instructions I followed again, I actually did copy over the mhn.db sqlite database file over to the new system. But, I'm still getting connection errors: 

```
Parsing config file: /opt/hpfeeds/geoloc.json
Traceback (most recent call last):
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
connected to @hp2
 -> errormessage from server: authfail.
Parsing config file: /opt/hpfeeds/geoloc.json
Traceback (most recent call last):
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
connected to @hp2
 -> errormessage from server: authfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
Parsing config file: /opt/hpfeeds/geoloc.json
Traceback (most recent call last):
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
connected to @hp2
 -> errormessage from server: authfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
```

**Comment by coonsmatthew** [comment]
Any ideas what I may be doing wrong @d1str0?

**Comment by coonsmatthew** [comment]
@dwdixon, adding you to this.

**Comment by d1str0** [comment]
So I think the issue here might be that when you recovered all of the old hpfeeds credentials, it overwrote the few credentials of local services, such as geoloc.

To fix this, we want to see what the current hpfeeds credentials are and change geoloc's config to use this instead (or of course we can just create all brand new creds for geoloc if you prefer).

On the mhn box, open the mongo console: `mongo` and then switch to the hpfeeds db: `use hpfeeds`

Then, list the entries in the "auth_key" collection: `db.auth_key.find()`

Specifically, we want to find the 'secret' for the geoloc user.

Copy the secret, open /opt/hpfeeds/geoloc.json and replace the existing secret. My guess is these are different.

Once you save the new secret, restart geoloc with `sudo supervisorctl restart geoloc`
