### ISSUE TITLE
Honeymap still not working 

### ISSUE THREAD

**Issue by nitrogen17** [threatstream/mhn#670]
Can anyone reproduce fresh installation of MHN if the Honeymap is working in the latest master branch? I did MHN and Sensor Installation in Public IP two times already but the Honeymap didn't work. All working fine except the **Honeymap**. Issue #664 dont work either.

All supervisor are working normal both mhn and sensor

MHN supervisorctl 
> geoloc                           RUNNING   pid 9670, uptime 3:45:47
> honeymap                         RUNNING   pid 9671, uptime 3:45:47
> hpfeeds-broker                   RUNNING   pid 22250, uptime 3:48:25
> mhn-celery-beat                  RUNNING   pid 11662, uptime 3:37:54
> mhn-celery-worker                RUNNING   pid 11743, uptime 3:36:54
> mhn-collector                     RUNNING   pid 11743, uptime 3:36:54
> mhn-uwsgi                        RUNNING   pid 11666, uptime 3:37:54
> mnemosyne                        RUNNING   pid 8299, uptime 3:46:30

Snort Sensor
> snort                       RUNNING   pid 7753, uptime 0:06:40

**Thanks!**

**Comment by jtsamas** [comment]
I did not do a fresh installation however I followed the instructions given by @d1str0 . Unfortunately I only got this error 

**mhn-collector: ERROR**  

Looking at my logs in **mhn-collector.log** and **mhn-collector.err**

**sudo tail  /var/log/mhn/mhn-collector.log**
  File "/opt/mhn/env/src/hpfeeds-logger/hpfeedslogger/processors.py", line 77, in geo_intel
AttributeError: 'Location' object has no attribute 'lattitude'
2019-06-20 14:32:51,633 - collector - ERROR - 'Location' object has no attribute 'lattitude'
Traceback (most recent call last):
  File "collector_v2.py", line 100, in on_message
    results = processor.process(identifier, channel, payload, ignore_errors=True)
  File "/opt/mhn/env/src/hpfeeds-logger/hpfeedslogger/processors.py", line 631, in process
  File "/opt/mhn/env/src/hpfeeds-logger/hpfeedslogger/processors.py", line 607, in geo_intelligence_enrichment
  File "/opt/mhn/env/src/hpfeeds-logger/hpfeedslogger/processors.py", line 77, in geo_intel
AttributeError: 'Location' object has no attribute 'lattitude'

 **sudo tail  /var/log/mhn/mhn-collector.err**
    src_ip=dec.src_ip,
         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "collector_v2.py", line 5, in <module>
    from hpfeedslogger import processors
  File "/opt/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 166
    src_ip=dec.src_ip,
         ^
SyntaxError: invalid syntax

**Comment by tiancu1980** [comment]
Honneymapo not show the map https://github.com/threatstream/mhn/issues/246

**Comment by nitrogen17** [comment]
I tried that @tiancu1980 but no luck. Anyway I have an idea based on that #246 . 

Instead of 
`sudo tcpdump -A -nnNN 'tcp port 10000' | grep -o '\{.*' --line-buffered`

Try to use
`sudo tcpdump -A -nnNN 'tcp port 3000' | grep -o '\{.*' --line-buffered`

port 3000 indicates to the Honeymap page, i used that 3000 to sniff if theres packet received in that  port and yes, i got packets

https://i.imgur.com/xsdMIAV.png
`{\"city\":\"Xinpu\",\"city2\":\"Singapore\",\"countrycode\":\"CN\",\"countrycode2\":\"SG\",\"latitude\":34.5997,\"latitude2\":1.2929,\"longitude\":119.1594,\"longitude2\":103.8547,\"type\":\"snort.alerts\"}`

**Comment by nitrogen17** [comment]
I found the culprit! It seems that there's a problem when you deploy mhn server or sensor in a **Singapore Public IP**. This issue is exact as my problem #256.

https://i.imgur.com/wpD7D4w.png
As you can see, theres no **SG** in mapData.paths indicating Singapore object and it returns **undefined**. 

The temporary fix is to make the return of function(e) parameter into already exisiting objects and the honeymap will work. 
https://i.imgur.com/0EM7BxL.png

**Comment by jtsamas** [comment]
@nitrogen17 kindly guide me on steps, maybe i have the same issue

**Comment by d1str0** [comment]
@nitrogen17 can you elaborate on your fix? What file is mapData.paths? Is this from the GeoLite2.mmdb? Or a script in honeymap? Unfortunately images don't help as much as text file links.

If you can elaborate I would love to fix this.

**Comment by nitrogen17** [comment]
Sure, I’ll iterate the problem from the start

1. I check if the honey map receives any data by using this command to port 3000
`sudo tcpdump -A -nnNN 'tcp port 3000' | grep -o '\{.*' --line-buffered`
2. Since I get the data from using that command from my dry attacks I doubted that the problem would be on the client side or UI
3. I check the honey map log by right click and inspect elements. I found this JQuery error
https://i.imgur.com/BoLUsUM.png
4. I debug it by inserting `console.log(e)` to check the content of undefined from the `getRegionName:function(e)` and it seems that the problem is when you have `SG` data the return type of of the function will be undefined and it causing JS error.
    1. So ill tried to put a code that if the data is **SG** then I’ll return the data of **PH**
		`if(e=='SG') return this.mapData.paths['PH'].name;`

You can check the code here
**Filename Path:** honeymap/client/extern/jquery-jvectormap-1.0.min.js
**Note:** This is only temporary fix to bypass error for **SG**
[Link](https://gist.githubusercontent.com/nitrogen17/da8867096638cc07da2da8dcaf3c4324/raw/8a05b2fe3da08a288a80ad3e00607fb4d4b325b9/jquery-jvectormap-1.0.min.js)


So far the problem would be on the Database, im not sure if it's the GeoLite2.mmdb but the data would be like this

https://i.imgur.com/wpD7D4w.png

The **SG** must be included there in order to fix this issue

**Comment by dykno** [comment]
#54

**Comment by dykno** [comment]
Also worth checking out #54 from a few years back if anybody is still bumping into this.
