### ISSUE TITLE
Honeymap not showing attacks

### ISSUE THREAD

**Issue by Bloopx3** [threatstream/mhn#687]
Hello newbie here,

Just set up mhn and a cowrie honeypot and got a couple of attacks.
However the "Map" is not showing any hits despite having hits in the sensor.

Went to check out geoloc.log and saw this:
```
AddressNotFoundError: The address 172.31.6.20 is not in the database.
invalid message {"peerIP": "141.98.81.81", "commands": [], "loggedin": null, "protocol": "ssh", "startTime": "2019-07-12T01:51:13.577992Z", "ttylog": null, "hostIP": "172.31.6.20", "peerPort": 33179, "session": "856eb02f840c", "urls": [], "hostPort": 22, "credentials": [["ftp", "ftp"], ["osmc", "osmc"], ["root", "support"]], "hashes": [], "endTime": "2019-07-12T01:51:23.702990Z", "version": "'SSH-2.0-OpenSSH_7.3'", "unknownCommands": []}
Traceback (most recent call last):
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 86, in on_message
    m = p(identifier, payload, gi)
  File "/opt/hpfeeds/examples/geoloc/processors.py", line 75, in cowrie_sessions
    return create_message('cowrie.sessions', identifier, gi, src_ip=dec.peerIP, dst_ip=dec.hostIP)
  File "/opt/hpfeeds/examples/geoloc/processors.py", line 163, in create_message
    geo2 = gi.city(dst_ip)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/geoip2/database.py", line 114, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/geoip2/database.py", line 195, in _model_for
    record = self._get(types, ip_address)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/geoip2/database.py", line 191, in _get
    "The address %s is not in the database." % ip_address)
```
Saw that the address not found is showing my local ip rather than the public ip address and not sure if that was the issue.
Any idea which part of the config I should change to solve this?

**Comment by d1str0** [comment]
Do you have a public IP for your MHN host?

**Comment by Bloopx3** [comment]
> Do you have a public IP for your MHN host?

Yes I do.

**Comment by d1str0** [comment]
If you change your IP in /opt/mhn/server/config.py (base_url) to your public IP, then restart all services (`sudo supervisorctl restart all`)

See if that works

**Comment by Bloopx3** [comment]
> If you change your IP in /opt/mhn/server/config.py (base_url) to your public IP, then restart all services (sudo supervisorctl restart all)
> See if that works

hmm. My config is already configured using the mhn public ip. The error shown above is my "cowrie" private ip.
My guess is when it writes data into the database it uses the cowrie private ip instead of its public ip.
Not sure where to change that

**Comment by d1str0** [comment]
/opt/cowrie/etc/cowrie.cfg
Uncomment the follwoing:

report_public_ip = true

**Comment by Bloopx3** [comment]
> /opt/cowrie/etc/cowrie.cfg
> Uncomment the follwoing:
> report_public_ip = true
> And then restart the service with sudo supervisorctl restart all

hey thanks! Will try that
